# What has been written to a file is in the file once the program is over, whether or not anything closed it.
import hashlib, os, subprocess, sys, tempfile

def run(label, code, *arguments):
    "Runs the code in a directory of its own, and says how it ended, what it printed and what is in each file that it left."
    with tempfile.TemporaryDirectory() as directory:
        done = subprocess.run([sys.executable, "-c", code, *arguments], cwd=directory, capture_output=True)
        files = {}
        for name in sorted(os.listdir(directory)):
            with open(os.path.join(directory, name), "rb") as file: data = file.read()
            files[name] = data if len(data) < 60 else (len(data), hashlib.md5(data).hexdigest())
        print(label, "->", done.returncode, done.stdout, done.stderr[-200:], files)

print("===== however it is left")
run("in a global", "f = open('a', 'w'); f.write('text')")
run("dropped at once", "open('a', 'w').write('text')")
run("a local of a function that has returned", "def g():\n    f = open('a', 'w'); f.write('text')\ng()")
run("in a list", "l = [open('a%d' % i, 'w') for i in range(5)]\nfor i, f in enumerate(l): f.write('text %d' % i)")
run("in a closure", "def g():\n    f = open('a', 'w')\n    return lambda s: f.write(s)\nw = g(); w('one '); w('two')")
run("in a generator that is not finished", "def g():\n    f = open('a', 'w'); f.write('text'); yield 1; f.close()\ni = g(); next(i)")
run("and the collector has been round", "import gc\nopen('a', 'w').write('text')\nf = open('b', 'w'); f.write('more'); del f\nfor _ in range(3): gc.collect()")
run("many", "for i in range(60): open('a%02d' % i, 'w').write('x' * i)\nimport os; print(len(os.listdir('.')))")
print("===== whatever kind it is")
run("binary", "open('a', 'wb').write(b'bytes')")
run("appending", "open('a', 'w').write('one')\nf = open('b', 'w'); f.write('1'); f.close(); g = open('b', 'a'); g.write('2')")
run("for reading too", "f = open('a', 'wb'); f.write(b'0123456789'); f.close()\ng = open('a', 'r+b'); g.seek(3); g.write(b'xy'); print(g.read(2)); g.write(b'z')")
run("text for reading too", "f = open('a', 'w+'); f.write('abcdef'); f.seek(0); print(f.read(2)); f.seek(0, 2); f.write('gh')")
run("exclusive", "open('a', 'x').write('new')")
run("not buffered", "open('a', 'wb', buffering=0).write(b'raw')")
run("a line at a time", "f = open('a', 'w', buffering=1); f.write('line\\nand part of another')")
run("a small buffer", "f = open('a', 'wb', buffering=4); f.write(b'ab'); f.write(b'cd'); f.write(b'e')")
run("a large buffer", "f = open('a', 'wb', buffering=1 << 20); f.write(b'x' * 100000)")
run("more than the buffer holds, and a little", "f = open('a', 'wb'); f.write(b'x' * 100000); f.write(b'tail')")
run("much text", "f = open('a', 'w')\nfor i in range(20000): f.write('line %d\\n' % i)")
run("UTF-16", "open('a', 'w', encoding='utf-16').write('h\\xe9llo')")
run("UTF-8 with a signature", "open('a', 'w', encoding='utf-8-sig').write('h\\xe9llo')")
run("line endings", "open('a', 'w', newline='\\r\\n').write('one\\ntwo\\n')")
run("what cannot be encoded", "f = open('a', 'w', encoding='ascii'); f.write('ok')\ntry: f.write('\\xe9')\nexcept UnicodeEncodeError as e: print(type(e).__name__)\nf.write(' still')")
run("put together by hand", "import io\nt = io.TextIOWrapper(io.BufferedWriter(io.FileIO('a', 'w')), encoding='utf-8'); t.write('layers')")
run("a BufferedWriter by hand", "import io\nb = io.BufferedWriter(io.FileIO('a', 'w')); b.write(b'two layers')")
run("a BufferedRandom by hand", "import io\nb = io.BufferedRandom(io.FileIO('a', 'w+')); b.write(b'random')")
run("a BufferedRWPair", "import io\np = io.BufferedRWPair(io.FileIO('a', 'w+'), io.FileIO('b', 'w')); p.write(b'pair')")
run("writing through", "import io\nt = io.TextIOWrapper(io.BufferedWriter(io.FileIO('a', 'w')), encoding='utf-8', write_through=True); t.write('through')")
run("by a descriptor", "import os\nf = open(os.open('a', os.O_WRONLY | os.O_CREAT), 'w'); f.write('descriptor')")
run("that it is not to close", "import os\nd = os.open('a', os.O_WRONLY | os.O_CREAT); f = open(d, 'w', closefd=False); f.write('kept open')")
run("derived classes", "import io\nclass T(io.TextIOWrapper): pass\nclass B(io.BufferedWriter): pass\nt = T(B(io.FileIO('a', 'w')), encoding='utf-8'); t.write('derived')")
run("whose flush() is its own", "import io, os\nclass B(io.BufferedWriter):\n    def flush(self): os.write(1, b'flush() '); super().flush()\nb = B(io.FileIO('a', 'w')); b.write(b'x')")
print("===== whatever wrote it")
run("print", "print('printed', 1, file=open('a', 'w'))")
run("writelines", "open('a', 'w').writelines(['one\\n', 'two\\n'])")
run("json", "import json\njson.dump({'k': [1, 2, None]}, open('a', 'w'))")
run("pickle", "import pickle\npickle.dump([1, 'two'], open('a', 'wb'), 2)")
run("csv", "import csv\ncsv.writer(open('a', 'w', newline='')).writerows([[1, 'a b'], [2, 'c,d']])")
run("pathlib", "import pathlib\npathlib.Path('a').open('w').write('path')")
run("configparser", "import configparser\nc = configparser.ConfigParser(); c['s'] = {'k': 'v'}; c.write(open('a', 'w'))")
run("sys.stdout is a file", "import sys\nsys.stdout = open('a', 'w'); print('to the file')")
run("and is put back", "import sys\nold = sys.stdout; sys.stdout = open('a', 'w'); print('to the file'); sys.stdout = old; print('to the terminal')")
run("sys.stderr is a file", "import sys\nsys.stderr = open('a', 'w'); print('to the file', file=sys.stderr)")
run("from what is registered with atexit", "import atexit\nf = open('a', 'w'); f.write('before; ')\natexit.register(lambda: f.write('at exit'))")
run("a file that is opened there", "import atexit\natexit.register(lambda: open('a', 'w').write('opened at exit'))")
print("===== however the program ends")
run("sys.exit()", "import sys\nf = open('a', 'w'); f.write('text'); sys.exit(3)")
run("SystemExit with something to say", "f = open('a', 'w'); f.write('text'); raise SystemExit('said')")
run("something is raised", "f = open('a', 'w'); f.write('text'); 1 / 0")
run("in a function", "def g():\n    f = open('a', 'w'); f.write('text'); 1 / 0\ng()")
run("os._exit(), when nothing is seen to", "import os\nf = open('a', 'w'); f.write('text'); os._exit(4)")
run("a signal, likewise", "import os, signal\nf = open('a', 'w'); f.write('text'); os.kill(os.getpid(), signal.SIGKILL)")
run("os.abort(), likewise", "import os\nf = open('a', 'w'); f.write('text'); os.abort()")
print("===== what has been seen to already")
run("closed", "f = open('a', 'w'); f.write('text'); f.close()")
run("with", "with open('a', 'w') as f: f.write('text')")
run("flushed", "f = open('a', 'w'); f.write('text'); f.flush(); print(open('a').read())")
run("flushed, and written to again", "f = open('a', 'w'); f.write('one'); f.flush(); f.write(' two')")
run("detached", "f = open('a', 'w'); f.write('text'); b = f.detach(); b.write(b' bytes')")
run("detached twice", "f = open('a', 'w'); f.write('text'); r = f.detach().detach(); r.write(b' raw')")
run("made over again", "import io\nb = io.BufferedWriter(io.FileIO('a', 'w')); b.write(b'lost'); b.__init__(io.FileIO('b', 'w')); b.write(b'kept')")
run("text made over again", "import io\nt = io.TextIOWrapper(io.BufferedWriter(io.FileIO('a', 'w')), encoding='utf-8'); t.write('lost'); t.__init__(io.BufferedWriter(io.FileIO('b', 'w')), encoding='utf-8'); t.write('kept')")
run("truncated", "f = open('a', 'wb'); f.write(b'0123456789'); f.truncate(4); f.write(b'xy')")
run("sought", "f = open('a', 'wb'); f.write(b'0123456789'); f.seek(2); f.write(b'xy')")
run("the descriptor was closed behind its back", "import os\nf = open('a', 'w'); f.write('text'); os.close(f.fileno())")
run("the raw file was closed", "f = open('a', 'w'); f.write('text'); f.buffer.raw.close()")
print("===== over something of a program's")
raw = "import io, os\nclass Raw(io.RawIOBase):\n    def writable(self): return True\n    def write(self, b):\n        os.write(1, b'write(%r) ' % bytes(b)); return len(b)\n"
run("it is given it", raw + "b = io.BufferedWriter(Raw()); b.write(b'owed'); print('the end', flush=True)")
run("text", raw + "t = io.TextIOWrapper(io.BufferedWriter(Raw()), encoding='utf-8'); t.write('owed'); print('the end', flush=True)")
run("text straight over it", raw + "t = io.TextIOWrapper(Raw(), encoding='utf-8'); t.write('owed'); print('the end', flush=True)")
run("it raises", raw.replace("return len(b)", "raise ZeroDivisionError") + "b = io.BufferedWriter(Raw()); b.write(b'owed'); print('the end', flush=True)")
run("it takes a little at a time", raw.replace("bytes(b)); return len(b)", "bytes(b[:3])); return min(3, len(b))") + "b = io.BufferedWriter(Raw()); b.write(b'0123456789'); print('the end', flush=True)")
run("over a BytesIO", "import io\ns = io.BytesIO(); b = io.BufferedWriter(s); b.write(b'x'); print(s.getvalue()); b.flush(); print(s.getvalue())")
print("done")
