# The prompt at which statements are typed and run one at a time, and input(). What is typed here comes down a pipe, and `python -i` takes it for typed all the same.
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.realpath(tempfile.mkdtemp())
os.chdir(HERE)
PLACES = sorted({os.path.realpath(sys.prefix), sys.prefix, os.path.realpath(sys.base_prefix)}, key=len, reverse=True)


def tidy(text):
    text = text.replace(HERE, "HERE")
    for place in PLACES:
        text = text.replace(place, "PREFIX")
    text = re.sub(r" at 0x[0-9a-f]+", " at 0x", text)
    text = re.sub(r'(?m)^  File "(?:<frozen [\w.]+>|PREFIX/[^"]+)", line \d+, in .*\n(?:    .*\n)*', "  (in the library)\n", text)
    text = re.sub(r"(?:  \(in the library\)\n)+", "  (in the library)\n", text)
    text = re.sub(r"(?m)^Python 3\.14\.\d+ .* on %s$" % sys.platform, "Python 3.14.N on this system", text)
    text = re.sub(r"(?m)^\S*/[Pp]ython[\d.]*: ", "PYTHON: ", text)
    return text


def run(typed, *arguments, env={}):
    environment = {"PATH": os.environ.get("PATH", ""), "HOME": HERE, "LC_ALL": "en_US.UTF-8", "PYTHONUTF8": "1"}
    environment.update(env)
    if isinstance(typed, str):
        typed = typed.encode()
    done = subprocess.run([sys.executable, *arguments], env=environment, input=typed, capture_output=True, timeout=60)
    return done.returncode, tidy(done.stdout.decode(errors="backslashreplace")), tidy(done.stderr.decode(errors="backslashreplace"))


def t(label, typed, *arguments, **k):
    print(label, "=>", ascii(run(typed, *(arguments or ("-i", "-q")), **k)))


def write(name, text):
    with open(os.path.join(HERE, name), "w") as f:
        f.write(text)
    return name


print("---- one line")
t("nothing", "")
t("a statement", "x = 1\n")
t("what it comes to is shown", "1 + 1\n'a'\nNone\n[1, 2]\n")
t("and kept", "5\n_ + 1\n_\nNone\n_\n")
t("several on a line", "x = 1; y = 2; x + y; y\n")
t("ending in a semicolon", "1;\n")
t("with no end to the line", "1 + 1")
t("a blank line", "\n\n1\n")
t("nothing but spaces", "   \n1\n")
t("nothing but a tab", "\t\n1\n")
t("nothing but a comment", "# c\n1\n")
t("a comment after spaces", "   # c\n1\n")
t("a comment after it", "1 # c\n")
t("a form feed", "\f\n1\n\f2\n")
t("indented", "  1\n2\n")
t("ended as on Windows", "1\r\n2\r\nif 1:\r\n    3\r\n\r\n")
t("ended as on an old Mac", "1\r2\r")
t("pass", "pass\n")
t("names", "__name__, __doc__, __package__, __spec__, __builtins__.__name__, sorted(globals())\n")
t("a long line", "x = '" + "a" * 20000 + "'\nlen(x)\n")

print("---- more than one line")
t("if", "if 1:\n    print('a')\n\n2\n")
t("if, on one line", "if 1: print('a')\n\n2\n")
t("if and else", "if 0:\n    1\nelse:\n    2\n\n")
t("else after a blank line", "if 0:\n    1\n\nelse:\n    2\n\n")
t("elif", "if 0:\n    1\nelif 1:\n    2\nelse:\n    3\n\n")
t("def", "def f(a,\n      b):\n    return a + b\n\nf(1, 2)\n")
t("class", "class C:\n    x = 1\n    def m(self):\n        return self.x\n\nC().m()\n")
t("decorated", "@staticmethod\ndef f():\n    return 1\n\nf()\n")
t("for and else", "for i in range(2):\n    i\nelse:\n    'done'\n\n")
t("while", "i = 0\nwhile i < 2:\n    i += 1\n\ni\n")
t("try", "try:\n    1 / 0\nexcept ZeroDivisionError as e:\n    e\nfinally:\n    'f'\n\n")
t("with", "import contextlib\nwith contextlib.nullcontext(3) as x:\n    x\n\n")
t("match", "match 1:\n    case 1:\n        'one'\n    case _:\n        'other'\n\n")
t("async def", "async def f():\n    return 1\n\nf().close()\n")
t("one in another", "if 1:\n    if 2:\n        if 3:\n            'deep'\n    'back'\n\n")
t("a line of spaces in it", "if 1:\n    1\n    \n    2\n\n")
t("fewer spaces than it is indented by", "if 1:\n    1\n  \n    2\n\n")
t("a comment in it", "if 1:\n    1\n# c\n    2\n\n")
t("a comment that is indented", "if 1:\n    1\n    # c\n    2\n\n")
t("something not indented straight after", "if 1:\n    1\n2\n")
t("brackets", "(1,\n 2,\n 3)\n")
t("a blank line in brackets", "[1,\n\n 2]\n")
t("a comment in brackets", "[1, # c\n # d\n 2]\n")
t("a call", "print(1,\n      2)\n")
t("a backslash", "1 + \\\n2\n")
t("a backslash and a blank line", "1 + \\\n\n")
t("a backslash and then the end", "1 + \\\n")
t("a backslash by itself", "\\\n1\n")
t("a string", "'''a\nb'''\n")
t("a blank line in a string", "'''a\n\nb'''\n")
t("an f-string", "x = 1\nf'''{x}\n{\nx + 1\n}'''\n")
t("a string in a block", "if 1:\n    '''a\n\nb'''\n\n")
t("a lambda in brackets", "f = (lambda:\n     1)\nf()\n")
t("a dict", "{\n 'a': 1,\n 'b': 2,\n}\n")

print("---- where it ends before it is over")
t("in a block", "if 1:\n    print('ran')\n")
t("in a block, with no end to the line", "if 1:\n    print('ran')")
t("after a colon", "if 1:\n")
t("in brackets", "(1,\n")
t("in brackets in a block", "if 1:\n    (1,\n")
t("in a string", "'''a\n")
t("in a string on one line", "'a\n1\n")
t("in an f-string", "f'''{1\n")
t("after a decorator", "@staticmethod\n")
t("after try", "try:\n    1\n")

print("---- what is wrong with it")
for wrong in ("x = = 1\n", "1 +\n", ")\n", "(1 2)\n", "(1,\n 2 3)\n", "print 'a'\n", "exec 'a'\n", "f(a for a in b, c)\n", "def f(:\n", "def f()\n", "if 1\n", "if 1:\n1\n", "if 1:\n    1\n  2\n", "if 1:\n\t1\n        2\n\n", "class\n", "x = 1 if 2\n", "a b\n", "1 = x\n", "f() = 1\n", "x = $\n", "x = 1e\n", "x = 0777\n", "x = 1__0\n", "'a' b'b'\n", "f'{'\n", "f'{a b}'\n", "f'{}'\n",
              "else:\n", "except:\n", "    x\n", "import\n", "from x import\n", "from . import *\nx\n", "def f():\nreturn\n", "for x in\n", "while:\n", "with:\n", "lambda: (yield)\n", "x = [1, 2\ny = 3\n", "{1: 2, 3}\n", "a, b += 1\n", "del 1\n", "x: int: 3\n", "try:\n    1\nx\n", "try:\n    1\n\n", "match 1:\n    x\n\n", "\xe9 = 1\n\xe9\n", "\u20ac\n", "x = '\\N{nope}'\n", "b'\xe9'\n", "1 if 1 else\n", "not\n", "*a\n", "**a\n", "a = *b\n", "print(a=1, 2)\n", "f(**a, *b)\n", "nonlocal x\n", "x = (yield)\n", "return\n", "break\n", "continue\n", "await x\n", "yield 1\n", "def f():\n    x = 1\n    global x\n\n", "def f(a, a): pass\n\n", "def f():\n    nonlocal q\n\n", "class C:\n    return\n\n", "async def f():\n    yield from x\n\n", "[x async for x in y]\n", "def f():\n    return 1\n  x\n\n", "(x := 1) = 2\n", "x = 1 +\n2\n", "'a' 'b' 1\n", "1 2 3\n4\n", "(\n)\n1)\n"):
    t(ascii(wrong), wrong + "'went on'\n")

print("---- no more is asked for so as to say what is wrong")
for wrong in ("(1 2\n", "f(a b\n", "[1 2\n", "{1: 2 3\n", "x = (a b\n", "f(a for a in b, c\n", "print(1 2\n", "(1 +\n2 3\n"):
    t(ascii(wrong), wrong + "'went on'\n")

print("---- what is warned of")
t("in what is read", "'\\d'\n")
t("in a block", "if 1:\n    '\\d'\n\n")
t("in what is compiled", "1 is 1\n")
t("both", "'\\d' is 1\n")
t("as an error", "'\\d'\n1 is 1\n'went on'\n", "-i", "-q", "-W", "error")
t("in a function", "def f():\n    try:\n        pass\n    finally:\n        return 1\n\n")
t("before something that is wrong", "'\\d' = = 1\n")
t("by the program", "import warnings\nwarnings.warn('w')\nwarnings.warn('w')\ndef f():\n    warnings.warn('in f')\n\nf()\n")

print("---- what is raised")
t("by a statement", "1 / 0\n'went on'\n")
t("by what was typed before", "def f():\n    return 1 / 0\n\ndef g():\n    return f()\n\ng()\n")
t("on a later line of it", "if 1:\n    x = 1\n    1 / 0\n\n")
t("what the code says it is from", "def f(): pass\n\nf.__code__.co_filename\ndef g(): pass\n\ng.__code__.co_filename\nimport sys\nsys._getframe().f_code.co_filename\n\n\nsys._getframe().f_code.co_filename\n")
t("what is kept of the source", "x = 1\nimport linecache\n[(k, v[2]) for k, v in sorted(linecache.cache.items()) if k.startswith('<stdin')]\nlinecache.getlines('<stdin-0>'), linecache.getlines('<stdin>')\n")
t("what is counted", "x = = 1\nimport sys\nsys._getframe().f_code.co_filename\nreturn\nsys._getframe().f_code.co_filename\n")
t("code that is written out and read back", "import marshal, sys\ndef f():\n    return [x for x in 'ab']\n\nc = marshal.loads(marshal.dumps(f.__code__))\nc.co_filename, c.co_firstlineno, eval(c)\nif 1:\n    top = sys._getframe().f_code\n    print('ran')\n\nexec(marshal.loads(marshal.dumps(top)))\n")
t("what is remembered", "1 / 0\nimport sys\nsys.last_exc, sys.last_type, sys.last_value, sys.last_traceback.tb_lineno\n")
t("with something that led to it", "try:\n    1 / 0\nexcept Exception as e:\n    raise ValueError('v') from e\n\n")
t("a group", "raise ExceptionGroup('g', [ValueError(1), TypeError(2)])\n")
t("a name that is nearly right", "value = 1\nvalu\n")
t("KeyboardInterrupt", "raise KeyboardInterrupt\n'went on'\n")
t("MemoryError", "raise MemoryError\n'went on'\n")
# Whether the last of them is shown is not the same from one release to another.
code, out, err = run("raise MemoryError\n" * 20 + "'went on'\n", "-i", "-q")
print("MemoryError over and over =>", code, ascii(out), err.count(">>> "))
t("what is not an exception", "raise 1\n'went on'\n")
t("in showing it", "class C:\n    def __repr__(self): return 1 / 0\n\nC()\n'went on'\n")
t("sys.excepthook", "import sys\nsys.excepthook = lambda *a: print('hooked', a[0].__name__)\n1 / 0\nx = = 1\n")
t("sys.excepthook that raises", "import sys\nsys.excepthook = lambda *a: 2 / 0\n1 / 0\n'went on'\n")
t("sys.displayhook", "import sys\nsys.displayhook = lambda v: print('shown', v)\n1\nNone\ndel sys.displayhook\n1\n'went on'\n")
t("what a SyntaxError has", "import sys\nx = = 1\ne = sys.last_exc\ne.args, e.filename, e.lineno, e.offset, e.text, e.end_lineno, e.end_offset\nif 1:\n    y = = 2\n\ne = sys.last_exc\ne.args\nreturn\ne = sys.last_exc\ne.args\ndef f():\n    x = 1\n    global x\n\ne = sys.last_exc\ne.args, e.text\n")

print("---- how it ends")
t("exit()", "exit()\n'not reached'\n")
t("quit()", "quit()\n'not reached'\n")
t("exit", "exit\n'went on'\n")
t("exit(3)", "exit(3)\n")
t("sys.exit", "import sys\nsys.exit(4)\n")
t("with a message", "raise SystemExit('a message')\n'not reached'\n")
t("in a function", "def f():\n    raise SystemExit(5)\n\nf()\n")
t("caught", "try:\n    exit(6)\nexcept SystemExit as e:\n    e.code\n\n'went on'\n")
t("what was registered", "import atexit\natexit.register(print, 'at exit')\n")
t("os._exit", "import os\nos._exit(7)\n")
t("what was printed and not sent on", "import sys\nsys.stdout.write('a')\nsys.stderr.write('b')\n")

print("---- the prompts")
t("others", "import sys\nsys.ps1 = 'one> '\nsys.ps2 = 'two> '\nif 1:\n    1\n\n")
t("that are not strings", "import sys\nclass P:\n    n = 0\n    def __str__(self):\n        P.n += 1\n        return '[%d] ' % P.n\n\nsys.ps1 = P()\n1\n2\n")
t("that cannot be made into strings", "import sys\nclass P:\n    def __str__(self): return 1 / 0\n\nsys.ps1 = P()\n1\n2\n")
t("that are numbers", "import sys\nsys.ps1 = 1\nsys.ps2 = None\nif 1:\n    2\n\n")
t("that are gone", "import sys\ndel sys.ps1\n1\ndel sys.ps2\nif 1:\n    2\n\n")
t("that are not ASCII", "import sys\nsys.ps1 = '\xe9\u20ac> '\n1\n")
t("what they are at first", "import sys\nsys.ps1, sys.ps2\n")
t("there are none until something is typed", "", "-c", "import sys; print(hasattr(sys, 'ps1'), hasattr(sys, 'ps2'))")
t("set beforehand", "1\n", "-i", "-c", "import sys; sys.ps1 = 'mine> '")

print("---- from __future__")
t("goes on being so", "from __future__ import annotations\ndef f(x: nope): pass\n\nf.__annotations__\n")
t("and is not so before", "def f(x: nope): pass\n\nf.__annotations__\n'went on'\n")
t("barry_as_FLUFL", "1 <> 2\nfrom __future__ import barry_as_FLUFL\n1 <> 2\n1 != 2\n")
t("braces", "from __future__ import braces\n'went on'\n")
t("what there is none of", "from __future__ import nope\n'went on'\n")
t("not first", "x = 1; from __future__ import annotations\n'went on'\n")
t("what is compiled from there", "from __future__ import annotations\nimport __future__\nbool(compile('1', 'f', 'eval').co_flags & __future__.annotations.compiler_flag)\n")

print("---- after something has been run")
t("-c", "x\n", "-i", "-c", "x = 5")
t("-c that prints", "x\n", "-i", "-c", "x = 5; print('ran')")
t("-c that raises", "x\n", "-i", "-c", "x = 5; 1 / 0")
t("-c that exits", "x\n", "-i", "-c", "import sys; x = 5; sys.exit(3)")
t("-c that exits with a message", "x\n", "-i", "-c", "import sys; x = 5; sys.exit('bye')")
t("and then exits again", "sys.exit(4)\n", "-i", "-c", "import sys; sys.exit(3)")
t("-c that is wrong", "1\n", "-i", "-c", "x = = 1")
t("a file", "x, __name__, '__file__' in globals(), type(__loader__).__name__\n", "-i", write("script.py", "x = 6\n"))
t("a file that raises", "x\nimport sys\nsys.last_exc\n", "-i", write("raises.py", "x = 7\n1 / 0\n"))
t("a file that is not there", "1\n", "-i", "nope.py")
t("a module", "x, __name__\n", "-i", "-m", "script")
t("with nothing typed", "", "-i", "-c", "print('ran')")
t("-", "print('this is typed')\n1\n", "-i", "-")
t("without -i", "1\nprint(2)\n", "-q")
t("PYTHONINSPECT", "x\n", "-c", "x = 8", env={"PYTHONINSPECT": "1"})
t("PYTHONINSPECT, empty", "x\n", "-c", "x = 8", env={"PYTHONINSPECT": ""})
t("PYTHONINSPECT, and -E", "x\n", "-E", "-c", "x = 8", env={"PYTHONINSPECT": "1"})
t("PYTHONINSPECT, which the program sets", "x\n", "-c", "import os; x = 9; os.environ['PYTHONINSPECT'] = '1'")
t("PYTHONINSPECT, with nothing run", "1\nprint(2)\n", env={"PYTHONINSPECT": "1"})

print("---- before anything is typed")
t("what is said", "1\n", "-i")
t("with -S", "1\n", "-i", "-S")
t("with -c", "1\n", "-i", "-c", "pass")
t("with -v it is said even so", "", "-c", "pass", "-q") 
write("startup.py", "print('starting', __name__, __file__)\nfrom_startup = 1\n")
t("PYTHONSTARTUP", "from_startup\n'__file__' in globals()\n", "-i", "-q", env={"PYTHONSTARTUP": os.path.join(HERE, "startup.py")})
t("not after something has been run", "'from_startup' in globals()\n", "-i", "-q", "-c", "pass", env={"PYTHONSTARTUP": os.path.join(HERE, "startup.py")})
t("not if nothing is typed", "print('from_startup' in globals())\n", "-q", env={"PYTHONSTARTUP": os.path.join(HERE, "startup.py")})
t("not with -E", "'from_startup' in globals()\n", "-i", "-q", "-E", env={"PYTHONSTARTUP": os.path.join(HERE, "startup.py")})
t("that is not there", "1\n", "-i", "-q", env={"PYTHONSTARTUP": os.path.join(HERE, "nope.py")})
t("that raises", "1\n", "-i", "-q", env={"PYTHONSTARTUP": os.path.join(HERE, write("bad-startup.py", "1 / 0\n"))})
t("that is wrong", "1\n", "-i", "-q", env={"PYTHONSTARTUP": os.path.join(HERE, write("wrong-startup.py", "x = = 1\n"))})
t("that exits", "1\n", "-i", "-q", env={"PYTHONSTARTUP": os.path.join(HERE, write("exiting-startup.py", "raise SystemExit(9)\n"))})
write("sitecustomize.py", "import sys, os\nkind = os.environ.get('HOOK')\nif kind == 'prints': sys.__interactivehook__ = lambda: print('hooked')\nif kind == 'raises': sys.__interactivehook__ = lambda: 1 / 0\nif kind == 'exits': sys.__interactivehook__ = lambda: sys.exit(8)\nif kind == 'none': del sys.__interactivehook__\n")
for kind in ("prints", "raises", "exits", "none"):
    t("sys.__interactivehook__ that " + kind, "1\n", "-i", "-q", env={"PYTHONPATH": HERE, "HOOK": kind})
    t("after something has been run", "1\n", "-i", "-q", "-c", "print('ran')", env={"PYTHONPATH": HERE, "HOOK": kind})
t("not if nothing is typed", "print(1)\n", "-q", env={"PYTHONPATH": HERE, "HOOK": "prints"})
t("what is told of", "1\n", "-i", "-q", "-c", "import sys; sys.addaudithook(lambda e, a: print('audit', e, a) if e.startswith('cpython.') else None)")

print("---- what is typed that is not text")
t("not UTF-8", b"'\xff'\n'went on'\n")
t("not UTF-8, further on", b"if 1:\n    '\xff'\n\n'went on'\n")
t("in another encoding", "'\xe9'\n".encode("latin-1"), "-i", "-q", env={"PYTHONIOENCODING": "latin-1"})
t("a zero", b"1\x002\n'went on'\n")
t("half a character", "'\U0001F600'\nlen(_)\n")

print("---- sys._baserepl()")
t("from a program", "1\nx\nexit(3)\n", "-c", "import sys; x = 5; sys._baserepl(); print('not reached')")
t("that comes to the end", "1\n", "-c", "import sys; print(sys._baserepl()); print('after')")

print("---- input()")
INPUT = """
import io, sys
def t(f):
    try:
        print(repr(f()))
    except BaseException as e:
        print(type(e).__name__, e)
"""
t("a line", "typed\n", "-c", "print(repr(input()))")
t("with a prompt", "typed\n", "-c", "print(repr(input('? ')))")
t("with no end to it", "typed", "-c", "print(repr(input()))")
t("an empty line", "\nmore\n", "-c", "print(repr(input()), repr(input()))")
t("nothing", "", "-c", "input()")
t("nothing, with a prompt", "", "-c", "input('? ')")
t("ended as on Windows", "typed\r\n", "-c", "print(repr(input()))")
t("several", "a\nb\nc\n", "-c", "print([input(str(i)) for i in range(3)])")
t("and what is left", "a\nb\nc\n", "-c", "import sys; print(repr(input()), repr(sys.stdin.read()))")
t("prompts that are not strings", "a\nb\nc\nd\n", "-c", "input(1); input(None); input(b'x'); input([1])")
t("a prompt that cannot be made into one", "a\n", "-c", "class P:\n    def __str__(self): return 1 / 0\ninput(P())")
t("too much", "a\n", "-c", "input(1, 2)")
t("by name", "a\n", "-c", "input(prompt='x')")
t("not UTF-8", b"\xff\n", "-c", "print(ascii(input()))")
t("what is on the way out goes first", "a\n", "-c", "import sys; sys.stdout.write('out'); sys.stderr.write('err'); input('? ')")
t("another sys.stdin", "", "-c", INPUT + "sys.stdin = io.StringIO('a\\nb'); t(input); t(input); t(input)")
t("that gives bytes", "", "-c", INPUT + "sys.stdin = io.BytesIO(b'a\\nb'); t(input); t(input); t(input)")
t("that gives something else", "", "-c", INPUT + "class F:\n    def readline(self): return 1\nsys.stdin = F(); t(input)")
t("that has no readline", "", "-c", INPUT + "sys.stdin = object(); t(input)")
t("that raises", "", "-c", INPUT + "class F:\n    def readline(self): return 1 / 0\nsys.stdin = F(); t(input)")
t("whose fileno raises", "", "-c", INPUT + "class F(io.StringIO):\n    def fileno(self): return 1 / 0\nsys.stdin = F('a\\n'); t(input)")
t("whose fileno is not a number", "", "-c", INPUT + "class F(io.StringIO):\n    def fileno(self): return 'x'\nsys.stdin = F('a\\n'); t(input)")
t("whose fileno is less than nothing", "", "-c", INPUT + "class F(io.StringIO):\n    def fileno(self): return -1\nsys.stdin = F('a\\n'); t(input)")
t("another sys.stdout", "a\n", "-c", INPUT + "out = sys.stdout; sys.stdout = io.StringIO(); x = input('? '); shown = sys.stdout.getvalue(); sys.stdout = out; print(repr(x), repr(shown))")
t("that cannot be written to", "a\n", "-c", INPUT + "class F:\n    def write(self, s): return 1 / 0\n    def flush(self): pass\nout = sys.stdout; sys.stdout = F()\ntry:\n    input('? ')\nexcept Exception as e:\n    sys.stdout = out; print(type(e).__name__)")
t("that cannot be flushed", "a\n", "-c", INPUT + "class F:\n    def write(self, s): pass\n    def flush(self): return 1 / 0\nout = sys.stdout; sys.stdout = F(); x = input('? '); sys.stdout = out; print(repr(x))")
for name in ("stdin", "stdout", "stderr"):
    t("no sys." + name, "a\n", "-c", INPUT + "keep = sys.%s; sys.%s = None\ntry:\n    input()\nexcept Exception as e:\n    sys.%s = keep; print(type(e).__name__, e)" % (name, name, name))
    t("sys.%s is gone" % name, "a\n", "-c", INPUT + "keep = sys.%s; del sys.%s\ntry:\n    input()\nexcept Exception as e:\n    sys.%s = keep; print(type(e).__name__, e)" % (name, name, name))
t("what is told of", "a\nb\n", "-c", "import sys; sys.addaudithook(lambda e, a: print('audit', e, a) if 'input' in e else None); input('? '); input()")
t("what it is", "", "-c", "print(input, input.__name__, input.__module__, input.__text_signature__, input.__doc__.split('.')[0])")
t("at the prompt, where what is typed has been read already", "x = input()\nhello = 1\nx\n")
