#!/usr/bin/env bash
# load6.sh — 6-way parallel load harness for flaky GIL-off race signatures.
#
# Runs a single threads test repeatedly across 6 concurrent workers with
# rotating --randomYieldSeed values, under host load generated by the workers
# themselves. This is the harness behind the ITEM 2 (ab17e)
# spawned-thread-butterfly-stress closure runs: 6 workers x RUNS_PER_WORKER
# runs each (default 20 -> 120 total). A run FAILS if jsc exits nonzero, or —
# for tests whose source prints a PASS marker — if the run output lacks PASS.
# Silent-assert tests (no PASS in source) pass on rc==0 alone; override the
# auto-detection with REQUIRE_PASS=0/1. Failure logs are kept, passing logs deleted.
#
# Usage:
#   Tools/threads/load6.sh [path/to/test.js]
#
# Environment:
#   JSC               jsc binary (default: WebKitBuild/Debug/bin/jsc)
#   OUT               failure-log directory (default: /tmp/load6-logs)
#   RUNS_PER_WORKER   runs per worker (default: 20 -> 120 total)
#   SEED_BASE         base for --randomYieldSeed rotation (default: 1000)
#   TIMEOUT_S         per-run timeout in seconds (default: 120)
#   REQUIRE_PASS      1 = require PASS marker, 0 = rc-only; default auto-detect from test source
#
# Exit code: number of failures (0 = clean).
#
# The GIL-off flag set below is the pinned verify configuration
# (docs/threads/UNGIL-HANDOUT.md); keep it in lockstep with run-tests.sh.

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

JSC=${JSC:-"$ROOT_DIR/WebKitBuild/Debug/bin/jsc"}
TEST=${1:-"$ROOT_DIR/JSTests/threads/jit/spawned-thread-butterfly-stress.js"}
OUT=${OUT:-/tmp/load6-logs}
RUNS_PER_WORKER=${RUNS_PER_WORKER:-20}
SEED_BASE=${SEED_BASE:-1000}
TIMEOUT_S=${TIMEOUT_S:-120}

[[ -x "$JSC" ]] || { echo "load6: jsc not found: $JSC" >&2; exit 2; }
[[ -f "$TEST" ]] || { echo "load6: test not found: $TEST" >&2; exit 2; }

# Silent-assert corpus tests (e.g. races/transition-vs-write.js) signal success
# purely via rc==0 from shouldBe asserts and never print PASS. Only require the
# PASS marker when the test source actually emits one. Override with
# REQUIRE_PASS=1 (force marker) or REQUIRE_PASS=0 (rc-only / --silent-pass mode).
if [[ -n "${REQUIRE_PASS:-}" ]]; then
    case "$REQUIRE_PASS" in
        0|1) ;;
        *) echo "load6: REQUIRE_PASS must be 0 or 1" >&2; exit 2;;
    esac
    require_pass=$REQUIRE_PASS
elif grep -q "PASS" "$TEST"; then
    require_pass=1
else
    require_pass=0
    echo "load6: $TEST does not print PASS; using rc-only pass criterion"
fi
mkdir -p "$OUT"

FLAGS=(--useJSThreads=1 --useThreadGIL=0 --useVMLite=1
       --useSharedAtomStringTable=1 --useSharedGCHeap=1
       --useThreadGILOffUnsafe=1 --useDollarVM=1)

worker() {
    local w=$1 i seed log rc
    for ((i = 0; i < RUNS_PER_WORKER; ++i)); do
        seed=$((SEED_BASE + w * 1000 + i))
        log="$OUT/w${w}-r${i}-s${seed}.log"
        timeout -k 5 "$TIMEOUT_S" "$JSC" "${FLAGS[@]}" \
            --randomYieldPeriod=64 --randomYieldSeed=$seed "$TEST" >"$log" 2>&1
        rc=$?
        if [[ $rc -ne 0 ]]; then
            mv "$log" "$OUT/FAIL-rc${rc}-w${w}-r${i}-s${seed}.log"
        elif [[ $require_pass -eq 1 ]] && ! grep -q "PASS" "$log"; then
            mv "$log" "$OUT/BAD-w${w}-r${i}-s${seed}.log"
        else
            rm -f "$log"
        fi
    done
}

for w in 0 1 2 3 4 5; do worker "$w" & done
wait

failures=$(ls "$OUT" 2>/dev/null | wc -l)
echo "load6: $((RUNS_PER_WORKER * 6)) runs, $failures failures (logs in $OUT)"
ls "$OUT" 2>/dev/null
exit "$failures"
