#!/usr/bin/env bash
# core-reaper.sh — extract all-thread backtraces from new scaling-suite cores, then delete them.
# Only touches cores whose generating command line contains 'threads/scaling' (this campaign's runs).
set -u
JSC=/root/WebKit/WebKitBuild/Release/bin/jsc
OUT=/root/WebKit/Tools/threads/bughunt/stw-watchdog/bts
mkdir -p "$OUT"
while true; do
    for c in /tmp/cores/core.*; do
        [ -e "$c" ] || continue
        # Skip cores younger than 30s (may still be written).
        age=$(( $(date +%s) - $(stat -c %Y "$c") ))
        [ $age -lt 30 ] && continue
        gen=$(gdb -batch -ex 'set pagination off' -ex quit "$JSC" "$c" 2>/dev/null | grep "Core was generated by" | head -1)
        if echo "$gen" | grep -q "threads/scaling"; then
            b="$OUT/$(basename "$c").bt"
            { echo "$gen"; gdb -batch -ex 'set pagination off' -ex 'thread apply all bt 30' "$JSC" "$c" 2>/dev/null | grep -v '^\['; } > "$b"
            echo "reaped $c -> $b"
            rm -f "$c"
        elif [ $age -gt 7200 ]; then
            : # foreign old core; leave alone
        fi
    done
    sleep 20
done
