// Made by lib/convert-termios-constants.py out of Modules/termios.c of CPython. It is not to be changed by hand.
// 278 numbers, each on the condition that CPython has it in the module on.

ADD_CONSTANT(B0);
ADD_CONSTANT(B50);
ADD_CONSTANT(B75);
ADD_CONSTANT(B110);
ADD_CONSTANT(B134);
ADD_CONSTANT(B150);
ADD_CONSTANT(B200);
ADD_CONSTANT(B300);
ADD_CONSTANT(B600);
ADD_CONSTANT(B1200);
ADD_CONSTANT(B1800);
ADD_CONSTANT(B2400);
ADD_CONSTANT(B4800);
ADD_CONSTANT(B9600);
ADD_CONSTANT(B19200);
ADD_CONSTANT(B38400);
#ifdef B57600
ADD_CONSTANT(B57600);
#endif
#ifdef B115200
ADD_CONSTANT(B115200);
#endif
#ifdef B230400
ADD_CONSTANT(B230400);
#endif
#ifdef B460800
ADD_CONSTANT(B460800);
#endif
#ifdef B500000
ADD_CONSTANT(B500000);
#endif
#ifdef B576000
ADD_CONSTANT(B576000);
#endif
#ifdef B921600
ADD_CONSTANT(B921600);
#endif
#ifdef B1000000
ADD_CONSTANT(B1000000);
#endif
#ifdef B1152000
ADD_CONSTANT(B1152000);
#endif
#ifdef B1500000
ADD_CONSTANT(B1500000);
#endif
#ifdef B2000000
ADD_CONSTANT(B2000000);
#endif
#ifdef B2500000
ADD_CONSTANT(B2500000);
#endif
#ifdef B3000000
ADD_CONSTANT(B3000000);
#endif
#ifdef B3500000
ADD_CONSTANT(B3500000);
#endif
#ifdef B4000000
ADD_CONSTANT(B4000000);
#endif
#ifdef CBAUDEX
ADD_CONSTANT(CBAUDEX);
#endif
ADD_CONSTANT(TCSANOW);
ADD_CONSTANT(TCSADRAIN);
ADD_CONSTANT(TCSAFLUSH);
#ifdef TCSASOFT
ADD_CONSTANT(TCSASOFT);
#endif
ADD_CONSTANT(TCIFLUSH);
ADD_CONSTANT(TCOFLUSH);
ADD_CONSTANT(TCIOFLUSH);
ADD_CONSTANT(TCOOFF);
ADD_CONSTANT(TCOON);
ADD_CONSTANT(TCIOFF);
ADD_CONSTANT(TCION);
ADD_CONSTANT(IGNBRK);
ADD_CONSTANT(BRKINT);
ADD_CONSTANT(IGNPAR);
ADD_CONSTANT(PARMRK);
ADD_CONSTANT(INPCK);
ADD_CONSTANT(ISTRIP);
ADD_CONSTANT(INLCR);
ADD_CONSTANT(IGNCR);
ADD_CONSTANT(ICRNL);
#ifdef IUCLC
ADD_CONSTANT(IUCLC);
#endif
ADD_CONSTANT(IXON);
ADD_CONSTANT(IXANY);
ADD_CONSTANT(IXOFF);
#ifdef IMAXBEL
ADD_CONSTANT(IMAXBEL);
#endif
#ifdef IUTF8
ADD_CONSTANT(IUTF8);
#endif
ADD_CONSTANT(OPOST);
#ifdef OLCUC
ADD_CONSTANT(OLCUC);
#endif
#ifdef ONLCR
ADD_CONSTANT(ONLCR);
#endif
#ifdef OCRNL
ADD_CONSTANT(OCRNL);
#endif
#ifdef ONOCR
ADD_CONSTANT(ONOCR);
#endif
#ifdef ONLRET
ADD_CONSTANT(ONLRET);
#endif
#ifdef OFILL
ADD_CONSTANT(OFILL);
#endif
#ifdef OFDEL
ADD_CONSTANT(OFDEL);
#endif
#ifdef OXTABS
ADD_CONSTANT(OXTABS);
#endif
#ifdef ONOEOT
ADD_CONSTANT(ONOEOT);
#endif
#ifdef NLDLY
ADD_CONSTANT(NLDLY);
#endif
#ifdef CRDLY
ADD_CONSTANT(CRDLY);
#endif
#ifdef TABDLY
ADD_CONSTANT(TABDLY);
#endif
#ifdef BSDLY
ADD_CONSTANT(BSDLY);
#endif
#ifdef VTDLY
ADD_CONSTANT(VTDLY);
#endif
#ifdef FFDLY
ADD_CONSTANT(FFDLY);
#endif
#ifdef NL0
ADD_CONSTANT(NL0);
#endif
#ifdef NL1
ADD_CONSTANT(NL1);
#endif
#ifdef NL2
ADD_CONSTANT(NL2);
#endif
#ifdef NL3
ADD_CONSTANT(NL3);
#endif
#ifdef CR0
ADD_CONSTANT(CR0);
#endif
#ifdef CR1
ADD_CONSTANT(CR1);
#endif
#ifdef CR2
ADD_CONSTANT(CR2);
#endif
#ifdef CR3
ADD_CONSTANT(CR3);
#endif
#ifdef TAB0
ADD_CONSTANT(TAB0);
#endif
#ifdef TAB1
ADD_CONSTANT(TAB1);
#endif
#ifdef TAB2
ADD_CONSTANT(TAB2);
#endif
#ifdef TAB3
ADD_CONSTANT(TAB3);
#endif
#ifdef XTABS
ADD_CONSTANT(XTABS);
#endif
#ifdef BS0
ADD_CONSTANT(BS0);
#endif
#ifdef BS1
ADD_CONSTANT(BS1);
#endif
#ifdef VT0
ADD_CONSTANT(VT0);
#endif
#ifdef VT1
ADD_CONSTANT(VT1);
#endif
#ifdef FF0
ADD_CONSTANT(FF0);
#endif
#ifdef FF1
ADD_CONSTANT(FF1);
#endif
#ifdef CIGNORE
ADD_CONSTANT(CIGNORE);
#endif
ADD_CONSTANT(CSIZE);
ADD_CONSTANT(CSTOPB);
ADD_CONSTANT(CREAD);
ADD_CONSTANT(PARENB);
ADD_CONSTANT(PARODD);
ADD_CONSTANT(HUPCL);
ADD_CONSTANT(CLOCAL);
#ifdef CIBAUD
ADD_CONSTANT(CIBAUD);
#endif
#ifdef CRTSCTS
ADD_CONSTANT(CRTSCTS);
#endif
#ifdef CRTS_IFLOW
ADD_CONSTANT(CRTS_IFLOW);
#endif
#ifdef CDTR_IFLOW
ADD_CONSTANT(CDTR_IFLOW);
#endif
#ifdef CDSR_OFLOW
ADD_CONSTANT(CDSR_OFLOW);
#endif
#ifdef CCTS_OFLOW
ADD_CONSTANT(CCTS_OFLOW);
#endif
#ifdef CCAR_OFLOW
ADD_CONSTANT(CCAR_OFLOW);
#endif
#ifdef MDMBUF
ADD_CONSTANT(MDMBUF);
#endif
ADD_CONSTANT(CS5);
ADD_CONSTANT(CS6);
ADD_CONSTANT(CS7);
ADD_CONSTANT(CS8);
#ifdef ALTWERASE
ADD_CONSTANT(ALTWERASE);
#endif
ADD_CONSTANT(ISIG);
ADD_CONSTANT(ICANON);
#ifdef XCASE
ADD_CONSTANT(XCASE);
#endif
ADD_CONSTANT(ECHO);
ADD_CONSTANT(ECHOE);
ADD_CONSTANT(ECHOK);
ADD_CONSTANT(ECHONL);
#ifdef ECHOCTL
ADD_CONSTANT(ECHOCTL);
#endif
#ifdef ECHOPRT
ADD_CONSTANT(ECHOPRT);
#endif
#ifdef ECHOKE
ADD_CONSTANT(ECHOKE);
#endif
#ifdef FLUSHO
ADD_CONSTANT(FLUSHO);
#endif
#ifdef NOKERNINFO
ADD_CONSTANT(NOKERNINFO);
#endif
ADD_CONSTANT(NOFLSH);
ADD_CONSTANT(TOSTOP);
#ifdef PENDIN
ADD_CONSTANT(PENDIN);
#endif
ADD_CONSTANT(IEXTEN);
#ifdef EXTPROC
ADD_CONSTANT(EXTPROC);
#endif
ADD_CONSTANT(VINTR);
ADD_CONSTANT(VQUIT);
ADD_CONSTANT(VERASE);
ADD_CONSTANT(VKILL);
ADD_CONSTANT(VEOF);
ADD_CONSTANT(VTIME);
#ifdef VSTATUS
ADD_CONSTANT(VSTATUS);
#endif
ADD_CONSTANT(VMIN);
#ifdef VSWTC
ADD_CONSTANT(VSWTC);
ADD_CONSTANT(VSWTCH);
#endif
ADD_CONSTANT(VSTART);
ADD_CONSTANT(VSTOP);
ADD_CONSTANT(VSUSP);
#ifdef VDSUSP
ADD_CONSTANT(VDSUSP);
#endif
ADD_CONSTANT(VEOL);
#ifdef VREPRINT
ADD_CONSTANT(VREPRINT);
#endif
#ifdef VDISCARD
ADD_CONSTANT(VDISCARD);
#endif
#ifdef VWERASE
ADD_CONSTANT(VWERASE);
#endif
#ifdef VLNEXT
ADD_CONSTANT(VLNEXT);
#endif
#ifdef VEOL2
ADD_CONSTANT(VEOL2);
#endif
#ifdef B7200
ADD_CONSTANT(B7200);
#endif
#ifdef B14400
ADD_CONSTANT(B14400);
#endif
#ifdef B28800
ADD_CONSTANT(B28800);
#endif
#ifdef B76800
ADD_CONSTANT(B76800);
#endif
#ifdef B460800
ADD_CONSTANT(B460800);
#endif
#ifdef B500000
ADD_CONSTANT(B500000);
#endif
#ifdef B576000
ADD_CONSTANT(B576000);
#endif
#ifdef B921600
ADD_CONSTANT(B921600);
#endif
#ifdef B1000000
ADD_CONSTANT(B1000000);
#endif
#ifdef B1152000
ADD_CONSTANT(B1152000);
#endif
#ifdef B1500000
ADD_CONSTANT(B1500000);
#endif
#ifdef B2000000
ADD_CONSTANT(B2000000);
#endif
#ifdef B2500000
ADD_CONSTANT(B2500000);
#endif
#ifdef B3000000
ADD_CONSTANT(B3000000);
#endif
#ifdef B3500000
ADD_CONSTANT(B3500000);
#endif
#ifdef B4000000
ADD_CONSTANT(B4000000);
#endif
#ifdef CBAUD
ADD_CONSTANT(CBAUD);
#endif
#ifdef CDEL
ADD_CONSTANT(CDEL);
#endif
#ifdef CDSUSP
ADD_CONSTANT(CDSUSP);
#endif
#ifdef CEOF
ADD_CONSTANT(CEOF);
#endif
#ifdef CEOL
ADD_CONSTANT(CEOL);
#endif
#ifdef CEOL2
ADD_CONSTANT(CEOL2);
#endif
#ifdef CEOT
ADD_CONSTANT(CEOT);
#endif
#ifdef CERASE
ADD_CONSTANT(CERASE);
#endif
#ifdef CESC
ADD_CONSTANT(CESC);
#endif
#ifdef CFLUSH
ADD_CONSTANT(CFLUSH);
#endif
#ifdef CINTR
ADD_CONSTANT(CINTR);
#endif
#ifdef CKILL
ADD_CONSTANT(CKILL);
#endif
#ifdef CLNEXT
ADD_CONSTANT(CLNEXT);
#endif
#ifdef CNUL
ADD_CONSTANT(CNUL);
#endif
#ifdef COMMON
ADD_CONSTANT(COMMON);
#endif
#ifdef CQUIT
ADD_CONSTANT(CQUIT);
#endif
#ifdef CRPRNT
ADD_CONSTANT(CRPRNT);
#endif
#ifdef CSTART
ADD_CONSTANT(CSTART);
#endif
#ifdef CSTOP
ADD_CONSTANT(CSTOP);
#endif
#ifdef CSUSP
ADD_CONSTANT(CSUSP);
#endif
#ifdef CSWTCH
ADD_CONSTANT(CSWTCH);
#endif
#ifdef CWERASE
ADD_CONSTANT(CWERASE);
#endif
#ifdef EXTA
ADD_CONSTANT(EXTA);
#endif
#ifdef EXTB
ADD_CONSTANT(EXTB);
#endif
#ifdef FIOASYNC
ADD_CONSTANT(FIOASYNC);
#endif
#ifdef FIOCLEX
ADD_CONSTANT(FIOCLEX);
#endif
#ifdef FIONBIO
ADD_CONSTANT(FIONBIO);
#endif
#ifdef FIONCLEX
ADD_CONSTANT(FIONCLEX);
#endif
#ifdef FIONREAD
ADD_CONSTANT(FIONREAD);
#endif
#ifdef IBSHIFT
ADD_CONSTANT(IBSHIFT);
#endif
#ifdef INIT_C_CC
ADD_CONSTANT(INIT_C_CC);
#endif
#ifdef IOCSIZE_MASK
ADD_CONSTANT(IOCSIZE_MASK);
#endif
#ifdef IOCSIZE_SHIFT
ADD_CONSTANT(IOCSIZE_SHIFT);
#endif
#ifdef NCC
ADD_CONSTANT(NCC);
#endif
#ifdef NCCS
ADD_CONSTANT(NCCS);
#endif
#ifdef NSWTCH
ADD_CONSTANT(NSWTCH);
#endif
#ifdef N_MOUSE
ADD_CONSTANT(N_MOUSE);
#endif
#ifdef N_PPP
ADD_CONSTANT(N_PPP);
#endif
#ifdef N_SLIP
ADD_CONSTANT(N_SLIP);
#endif
#ifdef N_STRIP
ADD_CONSTANT(N_STRIP);
#endif
#ifdef N_TTY
ADD_CONSTANT(N_TTY);
#endif
#ifdef TCFLSH
ADD_CONSTANT(TCFLSH);
#endif
#ifdef TCGETA
ADD_CONSTANT(TCGETA);
#endif
#ifdef TCGETS
ADD_CONSTANT(TCGETS);
#endif
#ifdef TCSBRK
ADD_CONSTANT(TCSBRK);
#endif
#ifdef TCSBRKP
ADD_CONSTANT(TCSBRKP);
#endif
#ifdef TCSETA
ADD_CONSTANT(TCSETA);
#endif
#ifdef TCSETAF
ADD_CONSTANT(TCSETAF);
#endif
#ifdef TCSETAW
ADD_CONSTANT(TCSETAW);
#endif
#ifdef TCSETS
ADD_CONSTANT(TCSETS);
#endif
#ifdef TCSETSF
ADD_CONSTANT(TCSETSF);
#endif
#ifdef TCSETSW
ADD_CONSTANT(TCSETSW);
#endif
#ifdef TCXONC
ADD_CONSTANT(TCXONC);
#endif
#ifdef TIOCCONS
ADD_CONSTANT(TIOCCONS);
#endif
#ifdef TIOCEXCL
ADD_CONSTANT(TIOCEXCL);
#endif
#ifdef TIOCGETD
ADD_CONSTANT(TIOCGETD);
#endif
#ifdef TIOCGICOUNT
ADD_CONSTANT(TIOCGICOUNT);
#endif
#ifdef TIOCGLCKTRMIOS
ADD_CONSTANT(TIOCGLCKTRMIOS);
#endif
#ifdef TIOCGPGRP
ADD_CONSTANT(TIOCGPGRP);
#endif
#ifdef TIOCGSERIAL
ADD_CONSTANT(TIOCGSERIAL);
#endif
#ifdef TIOCGSIZE
ADD_CONSTANT(TIOCGSIZE);
#endif
#ifdef TIOCGSOFTCAR
ADD_CONSTANT(TIOCGSOFTCAR);
#endif
#ifdef TIOCGWINSZ
ADD_CONSTANT(TIOCGWINSZ);
#endif
#ifdef TIOCINQ
ADD_CONSTANT(TIOCINQ);
#endif
#ifdef TIOCLINUX
ADD_CONSTANT(TIOCLINUX);
#endif
#ifdef TIOCMBIC
ADD_CONSTANT(TIOCMBIC);
#endif
#ifdef TIOCMBIS
ADD_CONSTANT(TIOCMBIS);
#endif
#ifdef TIOCMGET
ADD_CONSTANT(TIOCMGET);
#endif
#ifdef TIOCMIWAIT
ADD_CONSTANT(TIOCMIWAIT);
#endif
#ifdef TIOCMSET
ADD_CONSTANT(TIOCMSET);
#endif
#ifdef TIOCM_CAR
ADD_CONSTANT(TIOCM_CAR);
#endif
#ifdef TIOCM_CD
ADD_CONSTANT(TIOCM_CD);
#endif
#ifdef TIOCM_CTS
ADD_CONSTANT(TIOCM_CTS);
#endif
#ifdef TIOCM_DSR
ADD_CONSTANT(TIOCM_DSR);
#endif
#ifdef TIOCM_DTR
ADD_CONSTANT(TIOCM_DTR);
#endif
#ifdef TIOCM_LE
ADD_CONSTANT(TIOCM_LE);
#endif
#ifdef TIOCM_RI
ADD_CONSTANT(TIOCM_RI);
#endif
#ifdef TIOCM_RNG
ADD_CONSTANT(TIOCM_RNG);
#endif
#ifdef TIOCM_RTS
ADD_CONSTANT(TIOCM_RTS);
#endif
#ifdef TIOCM_SR
ADD_CONSTANT(TIOCM_SR);
#endif
#ifdef TIOCM_ST
ADD_CONSTANT(TIOCM_ST);
#endif
#ifdef TIOCNOTTY
ADD_CONSTANT(TIOCNOTTY);
#endif
#ifdef TIOCNXCL
ADD_CONSTANT(TIOCNXCL);
#endif
#ifdef TIOCOUTQ
ADD_CONSTANT(TIOCOUTQ);
#endif
#ifdef TIOCPKT
ADD_CONSTANT(TIOCPKT);
#endif
#ifdef TIOCPKT_DATA
ADD_CONSTANT(TIOCPKT_DATA);
#endif
#ifdef TIOCPKT_DOSTOP
ADD_CONSTANT(TIOCPKT_DOSTOP);
#endif
#ifdef TIOCPKT_FLUSHREAD
ADD_CONSTANT(TIOCPKT_FLUSHREAD);
#endif
#ifdef TIOCPKT_FLUSHWRITE
ADD_CONSTANT(TIOCPKT_FLUSHWRITE);
#endif
#ifdef TIOCPKT_NOSTOP
ADD_CONSTANT(TIOCPKT_NOSTOP);
#endif
#ifdef TIOCPKT_START
ADD_CONSTANT(TIOCPKT_START);
#endif
#ifdef TIOCPKT_STOP
ADD_CONSTANT(TIOCPKT_STOP);
#endif
#ifdef TIOCSCTTY
ADD_CONSTANT(TIOCSCTTY);
#endif
#ifdef TIOCSERCONFIG
ADD_CONSTANT(TIOCSERCONFIG);
#endif
#ifdef TIOCSERGETLSR
ADD_CONSTANT(TIOCSERGETLSR);
#endif
#ifdef TIOCSERGETMULTI
ADD_CONSTANT(TIOCSERGETMULTI);
#endif
#ifdef TIOCSERGSTRUCT
ADD_CONSTANT(TIOCSERGSTRUCT);
#endif
#ifdef TIOCSERGWILD
ADD_CONSTANT(TIOCSERGWILD);
#endif
#ifdef TIOCSERSETMULTI
ADD_CONSTANT(TIOCSERSETMULTI);
#endif
#ifdef TIOCSERSWILD
ADD_CONSTANT(TIOCSERSWILD);
#endif
#ifdef TIOCSER_TEMT
ADD_CONSTANT(TIOCSER_TEMT);
#endif
#ifdef TIOCSETD
ADD_CONSTANT(TIOCSETD);
#endif
#ifdef TIOCSLCKTRMIOS
ADD_CONSTANT(TIOCSLCKTRMIOS);
#endif
#ifdef TIOCSPGRP
ADD_CONSTANT(TIOCSPGRP);
#endif
#ifdef TIOCSSERIAL
ADD_CONSTANT(TIOCSSERIAL);
#endif
#ifdef TIOCSSIZE
ADD_CONSTANT(TIOCSSIZE);
#endif
#ifdef TIOCSSOFTCAR
ADD_CONSTANT(TIOCSSOFTCAR);
#endif
#ifdef TIOCSTI
ADD_CONSTANT(TIOCSTI);
#endif
#ifdef TIOCSWINSZ
ADD_CONSTANT(TIOCSWINSZ);
#endif
#ifdef TIOCTTYGSTRUCT
ADD_CONSTANT(TIOCTTYGSTRUCT);
#endif
#ifdef _POSIX_VDISABLE
ADD_CONSTANT(_POSIX_VDISABLE);
#endif
