// Made by lib/convert-fcntl-constants.py out of Modules/fcntlmodule.c of CPython. It is not to be changed by hand.
// 113 numbers, each on the condition that CPython puts it in the module on.

ADD_INT_MACRO(LOCK_SH);
ADD_INT_MACRO(LOCK_EX);
ADD_INT_MACRO(LOCK_NB);
ADD_INT_MACRO(LOCK_UN);
#ifdef LOCK_MAND
ADD_INT_MACRO(LOCK_MAND);
#endif
#ifdef LOCK_READ
ADD_INT_MACRO(LOCK_READ);
#endif
#ifdef LOCK_WRITE
ADD_INT_MACRO(LOCK_WRITE);
#endif
#ifdef LOCK_RW
ADD_INT_MACRO(LOCK_RW);
#endif
#ifdef F_DUPFD
ADD_INT_MACRO(F_DUPFD);
#endif
#ifdef F_DUPFD_CLOEXEC
ADD_INT_MACRO(F_DUPFD_CLOEXEC);
#endif
#ifdef F_GETFD
ADD_INT_MACRO(F_GETFD);
#endif
#ifdef F_SETFD
ADD_INT_MACRO(F_SETFD);
#endif
#ifdef F_GETFL
ADD_INT_MACRO(F_GETFL);
#endif
#ifdef F_SETFL
ADD_INT_MACRO(F_SETFL);
#endif
#ifdef F_GETLK
ADD_INT_MACRO(F_GETLK);
#endif
#ifdef F_SETLK
ADD_INT_MACRO(F_SETLK);
#endif
#ifdef F_SETLKW
ADD_INT_MACRO(F_SETLKW);
#endif
#ifdef F_OFD_GETLK
ADD_INT_MACRO(F_OFD_GETLK);
#endif
#ifdef F_OFD_SETLK
ADD_INT_MACRO(F_OFD_SETLK);
#endif
#ifdef F_OFD_SETLKW
ADD_INT_MACRO(F_OFD_SETLKW);
#endif
#ifdef F_GETOWN
ADD_INT_MACRO(F_GETOWN);
#endif
#ifdef F_SETOWN
ADD_INT_MACRO(F_SETOWN);
#endif
#ifdef F_GETPATH
ADD_INT_MACRO(F_GETPATH);
#endif
#ifdef F_GETSIG
ADD_INT_MACRO(F_GETSIG);
#endif
#ifdef F_SETSIG
ADD_INT_MACRO(F_SETSIG);
#endif
#ifdef F_RDLCK
ADD_INT_MACRO(F_RDLCK);
#endif
#ifdef F_WRLCK
ADD_INT_MACRO(F_WRLCK);
#endif
#ifdef F_UNLCK
ADD_INT_MACRO(F_UNLCK);
#endif
#ifdef F_GETLK64
ADD_INT_MACRO(F_GETLK64);
#endif
#ifdef F_SETLK64
ADD_INT_MACRO(F_SETLK64);
#endif
#ifdef F_SETLKW64
ADD_INT_MACRO(F_SETLKW64);
#endif
#ifdef FASYNC
ADD_INT_MACRO(FASYNC);
#endif
#ifdef F_SETLEASE
ADD_INT_MACRO(F_SETLEASE);
#endif
#ifdef F_GETLEASE
ADD_INT_MACRO(F_GETLEASE);
#endif
#ifdef F_NOTIFY
ADD_INT_MACRO(F_NOTIFY);
#endif
#ifdef F_DUPFD_QUERY
ADD_INT_MACRO(F_DUPFD_QUERY);
#endif
#ifdef F_EXLCK
ADD_INT_MACRO(F_EXLCK);
#endif
#ifdef F_SHLCK
ADD_INT_MACRO(F_SHLCK);
#endif
#ifdef F_SETPIPE_SZ
ADD_INT_MACRO(F_SETPIPE_SZ);
#endif
#ifdef F_GETPIPE_SZ
ADD_INT_MACRO(F_GETPIPE_SZ);
#endif
#ifndef __ANDROID__
#ifdef FICLONE
ADD_INT_MACRO(FICLONE);
#endif
#ifdef FICLONERANGE
ADD_INT_MACRO(FICLONERANGE);
#endif
#endif
#ifdef F_GETOWN_EX
ADD_INT_MACRO(F_GETOWN_EX);
ADD_INT_MACRO(F_SETOWN_EX);
ADD_INT_MACRO(F_OWNER_TID);
ADD_INT_MACRO(F_OWNER_PID);
ADD_INT_MACRO(F_OWNER_PGRP);
#endif
#ifdef F_GET_RW_HINT
ADD_INT_MACRO(F_GET_RW_HINT);
ADD_INT_MACRO(F_SET_RW_HINT);
ADD_INT_MACRO(F_GET_FILE_RW_HINT);
ADD_INT_MACRO(F_SET_FILE_RW_HINT);
#ifndef RWH_WRITE_LIFE_NOT_SET  // typo in Linux < 5.5
# define RWH_WRITE_LIFE_NOT_SET RWF_WRITE_LIFE_NOT_SET
#endif
ADD_INT_MACRO(RWH_WRITE_LIFE_NOT_SET);
ADD_INT_MACRO(RWH_WRITE_LIFE_NONE);
ADD_INT_MACRO(RWH_WRITE_LIFE_SHORT);
ADD_INT_MACRO(RWH_WRITE_LIFE_MEDIUM);
ADD_INT_MACRO(RWH_WRITE_LIFE_LONG);
ADD_INT_MACRO(RWH_WRITE_LIFE_EXTREME);
#endif
#ifdef F_FULLFSYNC
ADD_INT_MACRO(F_FULLFSYNC);
#endif
#ifdef F_NOCACHE
ADD_INT_MACRO(F_NOCACHE);
#endif
#ifdef F_DUP2FD
ADD_INT_MACRO(F_DUP2FD);
#endif
#ifdef F_DUP2FD_CLOEXEC
ADD_INT_MACRO(F_DUP2FD_CLOEXEC);
#endif
#ifdef F_READAHEAD
ADD_INT_MACRO(F_READAHEAD);
#endif
#ifdef F_RDAHEAD
ADD_INT_MACRO(F_RDAHEAD);
#endif
#ifdef F_ISUNIONSTACK
ADD_INT_MACRO(F_ISUNIONSTACK);
#endif
#ifdef F_KINFO
ADD_INT_MACRO(F_KINFO);
#endif
#ifdef F_CLOSEM
ADD_INT_MACRO(F_CLOSEM);
#endif
#ifdef F_MAXFD
ADD_INT_MACRO(F_MAXFD);
#endif
#ifdef F_GETNOSIGPIPE
ADD_INT_MACRO(F_GETNOSIGPIPE);
#endif
#ifdef F_SETNOSIGPIPE
ADD_INT_MACRO(F_SETNOSIGPIPE);
#endif
#ifdef FD_CLOEXEC
ADD_INT_MACRO(FD_CLOEXEC);
#endif
#ifdef DN_ACCESS
ADD_INT_MACRO(DN_ACCESS);
#endif
#ifdef DN_MODIFY
ADD_INT_MACRO(DN_MODIFY);
#endif
#ifdef DN_CREATE
ADD_INT_MACRO(DN_CREATE);
#endif
#ifdef DN_DELETE
ADD_INT_MACRO(DN_DELETE);
#endif
#ifdef DN_RENAME
ADD_INT_MACRO(DN_RENAME);
#endif
#ifdef DN_ATTRIB
ADD_INT_MACRO(DN_ATTRIB);
#endif
#ifdef DN_MULTISHOT
ADD_INT_MACRO(DN_MULTISHOT);
#endif
#ifdef HAVE_STROPTS_H
ADD_INT_MACRO(I_PUSH);
ADD_INT_MACRO(I_POP);
ADD_INT_MACRO(I_LOOK);
ADD_INT_MACRO(I_FLUSH);
ADD_INT_MACRO(I_FLUSHBAND);
ADD_INT_MACRO(I_SETSIG);
ADD_INT_MACRO(I_GETSIG);
ADD_INT_MACRO(I_FIND);
ADD_INT_MACRO(I_PEEK);
ADD_INT_MACRO(I_SRDOPT);
ADD_INT_MACRO(I_GRDOPT);
ADD_INT_MACRO(I_NREAD);
ADD_INT_MACRO(I_FDINSERT);
ADD_INT_MACRO(I_STR);
ADD_INT_MACRO(I_SWROPT);
#ifdef I_GWROPT
ADD_INT_MACRO(I_GWROPT);
#endif
ADD_INT_MACRO(I_SENDFD);
ADD_INT_MACRO(I_RECVFD);
ADD_INT_MACRO(I_LIST);
ADD_INT_MACRO(I_ATMARK);
ADD_INT_MACRO(I_CKBAND);
ADD_INT_MACRO(I_GETBAND);
ADD_INT_MACRO(I_CANPUT);
ADD_INT_MACRO(I_SETCLTIME);
#ifdef I_GETCLTIME
ADD_INT_MACRO(I_GETCLTIME);
#endif
ADD_INT_MACRO(I_LINK);
ADD_INT_MACRO(I_UNLINK);
ADD_INT_MACRO(I_PLINK);
ADD_INT_MACRO(I_PUNLINK);
#endif
#ifdef F_ADD_SEALS
ADD_INT_MACRO(F_ADD_SEALS);
ADD_INT_MACRO(F_GET_SEALS);
ADD_INT_MACRO(F_SEAL_SEAL);
ADD_INT_MACRO(F_SEAL_SHRINK);
ADD_INT_MACRO(F_SEAL_GROW);
ADD_INT_MACRO(F_SEAL_WRITE);
#ifdef F_SEAL_FUTURE_WRITE
ADD_INT_MACRO(F_SEAL_FUTURE_WRITE);
#endif
#endif
