#!/usr/bin/env python3
#
# Copyright (C) 2026 Apple Inc. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY APPLE INC. ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE INC. OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


# Makes PythonUnicodeDatabase.h out of Modules/unicodedata_db.h of CPython, and PythonUnicodeNames.h out of Modules/unicodename_db.h.
#
#     python3 convert-unicode-database.py <the directory that CPython's source is in> data > ../PythonUnicodeDatabase.h
#     python3 convert-unicode-database.py <the directory that CPython's source is in> names > ../PythonUnicodeNames.h
#
# The numbers are left as they are. What is changed is what C++ and this directory call things.
import re
import sys

directory, which = sys.argv[1:]
source = open(directory + {"data": "/Modules/unicodedata_db.h", "names": "/Modules/unicodename_db.h"}[which]).read()
version = re.search(r'#define UNIDATA_VERSION "(.*?)"', open(directory + "/Modules/unicodedata_db.h").read()).group(1)
python = re.search(r'#define PY_MAJOR_VERSION\s+(\d+)\n#define PY_MINOR_VERSION\s+(\d+)', open(directory + "/Include/patchlevel.h").read()).groups()

NAMES = {
    "_PyUnicode_DatabaseRecord": "DatabaseRecord",
    "_PyUnicode_Database_Records": "databaseRecords",
    "_PyUnicode_CategoryNames": "categoryNames",
    "_PyUnicode_BidirectionalNames": "bidirectionalNames",
    "_PyUnicode_EastAsianWidthNames": "eastAsianWidthNames",
    "TOTAL_FIRST": "totalFirst",
    "TOTAL_LAST": "totalLast",
    "reindex": "Reindex",
    "nfc_first": "nfcFirst",
    "nfc_last": "nfcLast",
    "decomp_prefix": "decompositionPrefixes",
    "SHIFT": "shift",
    "decomp_data": "decompositionData",
    "DECOMP_SHIFT": "decompositionShift",
    "decomp_index1": "decompositionIndex1",
    "decomp_index2": "decompositionIndex2",
    "COMP_SHIFT": "compositionShift",
    "comp_index": "compositionIndex",
    "comp_data": "compositionData",
    "change_record": "ChangeRecord",
    "change_records_3_2_0": "changeRecords_3_2_0",
    "changes_3_2_0_index": "changesIndex_3_2_0",
    "changes_3_2_0_data": "changesData_3_2_0",
    "get_change_3_2_0": "changeRecord_3_2_0",
    "normalization_3_2_0": "normalization_3_2_0",
    "NAME_MAXLEN": "nameMaxLength",
    "packed_name_dawg": "packedNameDawg",
    "dawg_pos_to_codepoint": "dawgPositionToCodePoint",
    "DAWG_CODEPOINT_TO_POS_SHIFT": "dawgCodePointToPositionShift",
    "DAWG_CODEPOINT_TO_POS_NOTFOUND": "dawgCodePointToPositionNotFound",
    "dawg_codepoint_to_pos_index1": "dawgCodePointToPositionIndex1",
    "dawg_codepoint_to_pos_index2": "dawgCodePointToPositionIndex2",
    "aliases_start": "aliasesStart",
    "aliases_end": "aliasesEnd",
    "name_aliases": "nameAliases",
    "named_sequence": "NamedSequence",
    "named_sequences_start": "namedSequencesStart",
    "named_sequences_end": "namedSequencesEnd",
    "named_sequences": "namedSequences",
    "seqlen": "length",
    "seq": "characters",
    "derived_name_range": "DerivedNameRange",
    "derived_name_ranges": "derivedNameRanges",
    "derived_name_prefixes": "derivedNamePrefixes",
    "prefixid": "prefix",
    "Py_UCS4": "char32_t",
    "Py_UCS2": "char16_t",
}

text = source
# What made it, which is said again below
text = re.sub(r"\A/\* this file was generated by .*? \*/\n+", "", text)
text = re.sub(r'#define UNIDATA_VERSION ".*?"\n', "", text)
text = re.sub(r"#define (\w+) (\d+)\n", lambda m: "static constexpr unsigned %s = %s;\n" % m.groups(), text)
text = text.replace("struct reindex{int start;short count,index;};", "struct reindex {\n    int start;\n    short count;\n    short index;\n};")
text = text.replace("static struct reindex ", "static const reindex ")
text = re.sub(r"typedef struct NamedSequence \{(.*?)\} named_sequence;", r"struct named_sequence {\1};", text, flags=re.S)
text = re.sub(r"typedef struct \{(.*?)\} derived_name_range;", r"struct derived_name_range {\1};", text, flags=re.S)


def literals(match):
    "An array of strings of C's, which may end with NULL, as an array of ASCIILiteral"
    body = re.sub(r"\n\s*NULL,?", "", match.group(2))
    return "static constexpr ASCIILiteral %s[] = {%s};" % (match.group(1), re.sub(r'("[^"]*")', r"\1_s", body))


text = re.sub(r"(?:static )?const char \*\s*(?:const )?(\w+)\[\] = \{(.*?)\};", literals, text, flags=re.S)
text = re.sub(r"^const (\w+ \w+\[\] = \{)", r"static const \1", text, flags=re.M)
text = re.sub(r"^static const (?=[\w ]+\[\] = \{|unsigned int \w+ = )", "static constexpr ", text, flags=re.M)
text = text.replace("static const change_record* get_change_3_2_0(", "inline const change_record* get_change_3_2_0(").replace("static Py_UCS4 normalization_3_2_0(", "inline Py_UCS4 normalization_3_2_0(")
text = text.replace("    if (n >= 0x110000) index = 0;\n", "    if (n >= 0x110000)\n        index = 0;\n").replace("switch(n)", "switch (n)").replace("[n>>8]", "[n >> 8]").replace("[(index<<8)+(n & 255)]", "[(index << 8) + (n & 255)]").replace("change_records_3_2_0+index", "change_records_3_2_0 + index")
text = re.sub(r"\b(%s)\b" % "|".join(sorted(NAMES, key=len, reverse=True)), lambda m: NAMES[m.group(1)], text)
text = re.sub(r"[ \t]+$", "", text, flags=re.M).strip("\n")

RECORDS = """// What there is to know about a character, but for what is in PythonUnicodeTypeDatabase.h
struct DatabaseRecord {
    unsigned char category; // Which of categoryNames
    unsigned char combining; // The canonical combining class
    unsigned char bidirectional; // Which of bidirectionalNames
    unsigned char mirrored;
    unsigned char eastAsianWidth; // Which of eastAsianWidthNames
    unsigned char normalizationQuickCheck; // Two bits for each of the forms
};

// What was otherwise in an earlier version. 255 is that it was not.
struct ChangeRecord {
    unsigned char bidirectionalChanged;
    unsigned char categoryChanged;
    unsigned char decimalChanged;
    unsigned char mirroredChanged;
    unsigned char eastAsianWidthChanged;
    double numericChanged;
};

static constexpr ASCIILiteral unidataVersion = "%s"_s;

""" % version

license = open(sys.argv[0]).read().split("\n\n\n")[0].split("\n", 2)[2]
print("/*\n" + "\n".join((" *" + line[1:]).rstrip() for line in license.split("\n")) + "\n */\n")
print("// This is made by lib/convert-unicode-database.py from Modules/%s of CPython %s.%s, which is made from version %s of the Unicode Character Database." % ({"data": "unicodedata_db.h", "names": "unicodename_db.h"}[which], python[0], python[1], version))
print("// It is not to be changed by hand.\n")
print("#pragma once\n")
print("#include <wtf/text/ASCIILiteral.h>\n")
print("namespace JSC { namespace Python { namespace UnicodeDatabase {\n")
print((RECORDS if which == "data" else "") + text)
print("\n} } } // namespace JSC::Python::UnicodeDatabase")
