#!/usr/bin/env python3
#
# Copyright (C) 2026 Apple Inc. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY APPLE INC. ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE INC. OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


# generate-builtin-descriptions.py <output.h> <builtin-descriptions.json> <builtin-descriptions-linux.json>
#
# Puts what dump-builtin-descriptions.py wrote into a header, for PythonSignatures.cpp, in the order of the keys so that they can be searched. What is not the same on Linux is there twice, and the preprocessor takes one.

import json
import sys

output, source, source_for_linux = sys.argv[1], sys.argv[2], sys.argv[3]
with open(source) as file:
    entries = json.load(file)
with open(source_for_linux) as file:
    on_linux = {entry[0]: entry for entry in json.load(file)}

KINDS = {
    "type": "Type",
    "module": "Module",
    "wrapper_descriptor": "WrapperDescriptor",
    "method_descriptor": "MethodDescriptor",
    "classmethod_descriptor": "ClassMethodDescriptor",
    "builtin_function_or_method": "BuiltinFunction",
    "staticmethod": "StaticMethod",
    "getset_descriptor": "GetSetDescriptor",
    "member_descriptor": "MemberDescriptor",
}


def literal(text, may_be_any=False):
    if text is None:
        return "{ }"
    escaped = []
    for character in text:
        if character == "\n":
            escaped.append("\\n")
        elif character in "\"\\":
            escaped.append("\\" + character)
        elif character == "?":
            escaped.append("\\?")  # So that there are no trigraphs.
        elif " " <= character <= "~":
            escaped.append(character)
        elif may_be_any:
            # In three digits, so that a digit that comes next is not taken for part of it.
            escaped.extend("\\%03o" % byte for byte in character.encode())
        else:
            raise ValueError("%r is not ASCII that can be printed" % character)
    # Not "..."_s, which finds out how long it is a character at a time where the standard library is GNU's. There are more characters here than the compiler will take steps over one constant.
    return '"%s"' % "".join(escaped)


def table(declaration, row):
    """One row for each key that `row` makes something of, which is given an entry and gives a line or None"""
    lines.append("static constexpr %s[] = {" % declaration)
    elsewhere = {entry[0]: entry for entry in entries}
    for key in sorted(elsewhere.keys() | on_linux.keys(), key=str.encode):
        usual = row(elsewhere[key]) if key in elsewhere else None
        linux = row(on_linux[key]) if key in on_linux and on_linux[key][1] is not None else None if key in on_linux else usual
        if usual == linux:
            lines.extend([usual] if usual else [])
            continue
        lines.append("#if OS(LINUX)" if linux else "#if !OS(LINUX)")
        lines.append(linux or usual)
        if linux and usual:
            lines.extend(["#else", usual])
        lines.append("#endif")
    lines.append("};")


def description(entry):
    key, kind, signature, doc, *layout = entry
    return None if kind == "text" else "    { %s, BuiltinDescription::Kind::%s, %s, %s }," % (literal(key), KINDS[kind], literal(signature), literal(doc))


def layout_of_type(entry):
    return "    { %s, %d, %d, %d, %d, %dul }," % ((literal(entry[0]),) + tuple(entry[4])) if len(entry) > 4 else None


def text(entry):
    return "    { %s, %s }," % (literal(entry[0]), literal(entry[3], True)) if entry[1] == "text" else None


lines = ["// Generated by generate-builtin-descriptions.py. Do not edit.", ""]
table("BuiltinDescription s_builtinDescriptions", description)
lines.append("")
table("BuiltinTypeLayout s_builtinTypeLayouts", layout_of_type)
lines.append("")
table("BuiltinText s_builtinTexts", text)
with open(output, "w") as file:
    file.write("\n".join(lines) + "\n")
