#!/usr/bin/env python3
#
# Copyright (C) 2026 Apple Inc. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY APPLE INC. ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE INC. OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# generate-library-sources.py <output.h> <module.py>...
#
# Puts the source of the parts of Python's library that are written in Python into a header, for PythonModules.cpp.

import os
import sys

output, inputs = sys.argv[1], sys.argv[2:]
lines = ["// Generated by generate-library-sources.py. Do not edit.", ""]
names = []
for path in inputs:
    name = os.path.splitext(os.path.basename(path))[0]
    names.append(name)
    with open(path, "rb") as file:
        data = file.read()
    lines.append("static constexpr unsigned char s_librarySource_%s[] = {" % name)
    for start in range(0, len(data), 24):
        lines.append("    " + " ".join("%d," % byte for byte in data[start:start + 24]))
    lines.append("};")
    lines.append("")
lines.append("static constexpr LibrarySource s_librarySources[] = {")
for name in names:
    lines.append('    { "%s"_s, s_librarySource_%s },' % (name, name))
lines.append("};")
with open(output, "w") as file:
    file.write("\n".join(lines) + "\n")
