#!/usr/bin/env python3
#
# Copyright (C) 2026 Apple Inc. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY APPLE INC. ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE INC. OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


# generate-builtin-descriptions.py <output.h> <builtin-descriptions.json>
#
# Puts what dump-builtin-descriptions.py wrote into a header, for PythonSignatures.cpp, in the order of the keys so that they can be searched.

import json
import sys

output, source = sys.argv[1], sys.argv[2]
with open(source) as file:
    entries = json.load(file)

KINDS = {
    "type": "Type",
    "module": "Module",
    "wrapper_descriptor": "WrapperDescriptor",
    "method_descriptor": "MethodDescriptor",
    "classmethod_descriptor": "ClassMethodDescriptor",
    "builtin_function_or_method": "BuiltinFunction",
    "staticmethod": "StaticMethod",
    "getset_descriptor": "GetSetDescriptor",
    "member_descriptor": "MemberDescriptor",
}


def literal(text):
    if text is None:
        return "{ }"
    escaped = []
    for character in text:
        if character == "\n":
            escaped.append("\\n")
        elif character in "\"\\":
            escaped.append("\\" + character)
        elif character == "?":
            escaped.append("\\?")  # So that there are no trigraphs.
        elif " " <= character <= "~":
            escaped.append(character)
        else:
            raise ValueError("%r is not ASCII that can be printed" % character)
    return '"%s"_s' % "".join(escaped)


lines = ["// Generated by generate-builtin-descriptions.py. Do not edit.", "", "static constexpr BuiltinDescription s_builtinDescriptions[] = {"]
entries.sort(key=lambda entry: entry[0].encode())
for key, kind, signature, doc, *layout in entries:
    lines.append("    { %s, BuiltinDescription::Kind::%s, %s, %s }," % (literal(key), KINDS[kind], literal(signature), literal(doc)))
lines.append("};")
lines.append("")
lines.append("static constexpr BuiltinTypeLayout s_builtinTypeLayouts[] = {")
for key, kind, signature, doc, *layout in entries:
    if layout:
        lines.append("    { %s, %d, %d, %d, %d, %dul }," % ((literal(key),) + tuple(layout[0])))
lines.append("};")
with open(output, "w") as file:
    file.write("\n".join(lines) + "\n")
