/*
 * Copyright (C) 2019 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#pragma once

#if USE(BUN_JSC_ADDITIONS)

#include "JSCPrimordialsTable.h"
#include <cstdint>

namespace JSC {

// Primordials are tamper-proof references to the original ECMAScript built-ins,
// exposed to builtin JavaScript as link-time constants with Node.js's primordial
// naming, so modules ported from Node's lib/ keep their call sites:
//
//     @ArrayPrototypePush.@call(array, value);   // prototype method
//     @ObjectDefineProperty(obj, key, desc);     // static method
//     @MapPrototypeGetSize.@call(map);           // accessor getter
//     @SymbolIterator                            // value
//     @ArrayPrototype                            // a holder object itself
//
// Each primordial is a lazy link-time constant, materialized on the first
// CodeBlock link that references it. The pristine source is one of:
//
//   - the holder's own property, snapshotted at the holder's creation
//     (JSGlobalObject::snapshotPrimordialsFromHolder) before user code can
//     reach the holder: end of JSGlobalObject::init() for the eager holders,
//     and the LazyClassStructure / LazyProperty / static-table PropertyCallback
//     that creates a lazy holder. This is a key lookup + getDirect + pointer
//     store per entry; it does not reify, allocate on, or transition the holder.
//   - the holder's ClassInfo static hash tables, which user code cannot
//     mutate. A property still lazy at link time is looked up in the tables of
//     the (possibly freshly created) holder. If the holder still holds the
//     untouched entry, it is reified there (a one-time structure transition
//     on that holder) so the primordial and the property share one identity;
//     otherwise a fresh, un-installed copy is built from the immutable entry.
//   - for Self entries, the holder object itself, which JSC reaches through
//     its own accessors, never through the (mutable) global bindings.
//
// A key present in neither an own property nor a table is a builtin the
// current configuration does not expose (e.g. runtime-flagged); its primordial
// is a function that throws when called instead of a crash at capture time. An
// embedder that replaces a builtin during its own global setup calls
// overridePrimordialsFromHolder() so the primordial is what user code sees.
//
// The per-holder tables in JSCPrimordialsTable.h are generated by
// src/codegen/generate-primordials.ts in oven-sh/bun from Node.js's primordials
// construction applied to this engine, as
//
//     JSC_FOREACH_PRIMORDIAL_<Holder>(V)  →  V(name, key, kind)
//
// where key is PROP("string") | SYM(wellKnownSymbolName) | SELF and kind is
//     Method   value is a function (data property or table entry)
//     Getter   value is the accessor's getter function
//     Setter   value is the accessor's setter function
//     Value    value is an own object or symbol (constructor prototypes, well-known symbols)
//     Self     value is the holder object itself
// JSC_FOREACH_PRIMORDIAL_NAME(V) is the union whose expansion order defines each
// primordial's link-time-constant index; JSC_FOREACH_PRIMORDIAL_HOLDER(H) enumerates
// holders in that same order (eager first, then lazy).

enum class PrimordialHolder : uint8_t {
#define DECLARE_PRIMORDIAL_HOLDER(Holder) Holder,
    JSC_FOREACH_PRIMORDIAL_HOLDER(DECLARE_PRIMORDIAL_HOLDER)
#undef DECLARE_PRIMORDIAL_HOLDER
};

enum class PrimordialKind : uint8_t {
    Method,
    Getter,
    Setter,
    Value,
    Self,
};

#define JSC_COUNT_PRIMORDIAL(name, key, kind) 1 +
static constexpr unsigned numberOfPrimordials = JSC_FOREACH_PRIMORDIAL_NAME(JSC_COUNT_PRIMORDIAL) 0;
#undef JSC_COUNT_PRIMORDIAL

} // namespace JSC

#endif // USE(BUN_JSC_ADDITIONS)
