# One piece of source for each thing that can be said to be wrong with source, the shortest that there is in ../audits/syntax-errors.py.

import _warnings

_warnings.filters.insert(0, ("ignore", None, Warning, None, 0))
SOURCES = [
    '\t3',
    '\nclass Cls[T]:\n    nonlocal T\n',
    '\ndef outer():\n    X = 1\n    def inner[X]():\n        nonlocal X\n    return X\n',
    '\nfor abc in range(10):\n    try:\n        pass\n    finally:\n        try:\n',
    '\nfrom __future__ import *\n',
    '\nfrom __future__ import nested_scopes\nfrom __future__ import rested_snopes  # typo error here: nested => rested\n',
    '\nmatch ...:\n    case "a" | a:\n        pass\n',
    '\nmatch ...:\n    case 0+0:\n        pass\n',
    '\nmatch ...:\n    case 0j+0:\n        pass\n',
    '\nmatch ...:\n    case Class(a=_, a=_):\n        pass\n',
    '\nmatch ...:\n    case MyClass(x, x):\n        pass\n',
    '\nmatch ...:\n    case _ | _:\n        pass\n',
    '\nmatch ...:\n    case a | "a":\n        pass\n',
    '\nmatch ...:\n    case a, *b, c, *d, e:\n        pass\n',
    '\nmatch ...:\n    case a, a:\n        pass\n',
    '\nmatch ...:\n    case f"":\n        pass\n',
    '\nmatch ...:\n    case x | [_ as x] if x:\n        pass\n',
    '\nmatch ...:\n    case {"a": _, "a": _}:\n        pass\n',
    '\nmatch ...:\n    case {0: _, -0: _}:\n        pass\n',
    '\nmatch ...:\n    case {0: _, 0.0: _}:\n        pass\n',
    '\nmatch ...:\n    case {0: _, 0j: _}:\n        pass\n',
    '\nmatch ...:\n    case {0: _, False: _}:\n        pass\n',
    '\nmatch ...:\n    case {f"": _}:\n        pass\n',
    '\ntry:\n    raise ValueError\nexcept* Exception as e:\n    break\n',
    '!',
    '"',
    '"""blech',
    '"blech\\"',
    "'A' object has no attribute 'x'",
    "'\\N'",
    "'\\U'",
    "'\\u' ",
    "'\\x' ",
    "'str literal' t'{what}-string literal'",
    '(',
    '((a, b) := (1, 2))',
    '(): int\n',
    '(True := 1)\n',
    '(lambda: x := 1)',
    '(x for x in x) = 1\n',
    '(x): (await 42)',
    '(x): (y := 3)',
    '(x): (yield)',
    '(x): [y async for y in x]',
    '(yield i) = 2',
    ')',
    '*a',
    '*a = range(10) # doctest:+ELLIPSIS\n',
    '+ not 3\n',
    '-O=0',
    '... = 1\n',
    '012',
    '0b',
    '0b2',
    '0b42',
    '0e',
    '0o',
    '0o8',
    '0x',
    '1\x02  ',
    '1 = 1\n',
    '1!=2=',
    '1+2 = \n',
    '3=',
    'A[*]\n',
    "BF''",
    'C()=',
    "FUR''",
    "Fu''",
    'None += 0',
    'None = 0',
    'True = 0\n',
    '[',
    '[(*a)\n',
    '[(yield x) for x in ()]',
    '[*b, *c] = range(10) # doctest:+ELLIPSIS\n',
    '[*x for x in xs]',
    '[]: int\n',
    '[a, b] += 1, 2\n',
    '[i := 0 for i in range(5)]',
    '[i for i in (i := range(5))]',
    '[i for i in range(10)] = (1, 2, 3)',
    '[i for i in range(5) if (j := 0) for j in range(5)]',
    '[x for x if range(1)]\n',
    '[x if y]',
    '[x,y for x,y in range(100)]\n',
    '[z=3]\n',
    '[}',
    '\\',
    '\\"',
    ']',
    '__debug__ = 1',
    'a if 1 else b = 1\n',
    'async def foo():\n            yield\n            return 123\n',
    'async def foo():\n            yield from 123\n',
    'async for a in b: pass',
    'async with a as b: pass',
    'await y',
    "b'' f''",
    "b'\\x' ",
    'break',
    "bu'' ",
    'class A:\n    def f(self):\n        nonlocal __x\n',
    'class A[**P = [(yield), int]]: pass\n',
    'class A[*Ts = (yield)]: pass\n',
    'class A[T = (yield)]: pass\n',
    'class A[T]((await 3)): ...\n',
    'class A[T]((x := 3)): ...\n',
    'class A[T]((yield 3)): ...\n',
    'class A[__classdict__]: pass',
    'class Foo():\n            [(42, 1 + ((( j := i )))) for i in range(5)]\n',
    'class X[T: (yield)]: pass',
    'class X[T]([(x := 3) for _ in range(2)] and B): pass',
    'class a:',
    'continue',
    'def a-b',
    'def f():\n    global x\n    x: int\n',
    'def f():\n    nonlocal x\n',
    'def f():\n    nonlocal x\n    x: int\n',
    'def f():\n    print(x)\n    global x\n',
    'def f():\n    x = 1\n    def g():\n        print(x)\n        nonlocal x\n',
    'def f():\n    x = 1\n    def g():\n        x = 2\n        nonlocal x\n',
    'def f():\n    x = 1\n    global x\n',
    'def f():\n  from _ import *',
    'def f():\n  global x\n  nonlocal x',
    'def f():  await arange(10)\n',
    'def f(*): pass',
    'def f(**kwargs, /): pass',
    'def f(*, /, a): pass',
    'def f(/, a): pass',
    'def f(a): global a; a = 1',
    'def f(a, /, c, /): pass',
    'def f(a=1, b): pass',
    'def f(p1, *, k1, **k1):\n  pass\n',
    'def f(p1, *, p1=100):\n  pass\n',
    'def f(x):\n  nonlocal x',
    'def f(x): global x',
    'def f(x, x):\n  pass',
    'def f[T: (int, (yield))](): pass\n',
    'def f[T: [(x := 3) for _ in range(2)]](): pass',
    'def fn():\n    name_annot: int\n    global name_annot\n',
    'def fn():\n    name_assign = 1\n    global name_assign\n',
    'def fn():\n    print(name_use)\n    global name_use\n',
    'def fn(name_param):\n    global name_param\n',
    'def g(): ((yield x) for x in ())',
    'def g(): {(yield x) for x in ()}',
    'def g(): {(yield x): x for x in ()}',
    'def gen(): yield t"{breakyield 1)}"\n',
    'def p( (self): return 7\n',
    'def some[]()\n',
    'def with_stmt():\n    with x: \n',
    'def x():',
    'del (a := 5)',
    'del (a if True else b)',
    'del *x',
    'del +a',
    'del 1',
    'del None',
    'del __debug__\n',
    "del f''",
    'del f()',
    'exec f(a+b,c)',
    'f"',
    'f"""',
    'f"{1 1:',
    'f"{1+2:{1+2:{1+1:{1}}}}"',
    "f'' = 3",
    "f'{!'",
    'f\'{"s"!r{":10"}}\'',
    'f\'{"s"!{"r"}}\'',
    "f'{'",
    "f'{)#}'",
    "f'{,}'",
    "f'{1!=2=}'=",
    "f'{1:d\n}'",
    "f'{1=}{1;'",
    "f'{3!:'",
    "f'{3!ss}'",
    "f'{3:'",
    "f'{:'",
    "f'{='",
    "f'{C=]'",
    "f'{lambda :}'",
    "f'{}'",
    "f'}'",
    'f() += 1\n',
    'f() = 1',
    'f(): int\n',
    "f(**kwargs={'a': 1})\n",
    'f(**x, *y)\n',
    'f(*args=[0])\n',
    'f(1, x=2, *(3,4), x=5)',
    'f(False=1)\n',
    'f(a=)\n',
    'f(a=23, a=234)\n',
    'f(p, k1=50, *(1,2), k1=100)',
    'f(p, k=1, p2)',
    'f(x for x in L,)\n',
    'foo(1=2)',
    'for a in b:',
    'from __future__ import braces',
    'from __future__ import doesnt_exist',
    'from a import (\n  b as [],\n)\n',
    'from a import (\n  b as f())\n',
    'from t import x,\n',
    "ft'{x=}'\n",
    'func(\n    a=["unclosed], # Need a quote in this comment: "\n    b=2,\n)\n',
    'if 1:',
    'if 1:\n            import _testcapi\n            _testcapi.run_in_subinterp("[0]*',
    'if 1:\n  foo()\n bar()',
    'if True:\n if True:\n  if True:   \n',
    'if a % 2 == 0:\n    pass\nelse:\n    pass\nelif a % 2 == 1:\n    pass\n',
    'if a:\n pass\nelif b:',
    'if a:\n pass\nelif b:\n pass\nelse:',
    'if x.a = 3:\n   pass\n',
    'import',
    'import a as b.c\n',
    'import a from b\n',
    'import a, a.b as 1\n',
    'import a.b as (a, b)\n',
    'import x as None',
    "int(**{'base': 10}, '2')",
    'lambda (x, y, z), w: None\n',
    'lambda *b,*d: None\n',
    'lambda a,**b=3: None\n',
    'lambda a,*b=3,c: None\n',
    'lambda a,a:0',
    'lambda a,d=,c: None\n',
    'lambda a=1,/*,b,c: None\n',
    'lambda x: x = 2',
    'match ...:\n  case (32 as x) | (42 as a()):\n    ...\n',
    'match ...:\n  case 42 as (a, b):\n    ...\n',
    'match ...:\n  case 42 as 1+2+4:\n    ...\n',
    'match ...:\n  case 42 as _:\n    ...\n',
    'match ...:\n  case 42 as a.b:\n    ...\n',
    'match ...:\n  case Foo(z=1, x, y=2):\n    ...\n',
    'match something:\n    case []:\n        ...\n    case {}:\npass\n',
    'match something:\n    case []:\npass\n',
    'match something:\npass\n',
    'n = 1; n += 1; n *= 3; n -= 1; n //= 2; 5 **= 3; n %= 5; n <<= 4; n |= 1; n &= 0xff; n ^= 2; n >>= 1; print(n)\n',
    'nonlocal x',
    'print\x17("Hello")',
    'print p;',
    'return',
    'show("global is attribute", lambda: (globals():=__setitem__("via_dict", 2), me.via_dict, via_dict)[1:])\n',
    "t'",
    "t'''",
    "t'{!x}'",
    "t'{'",
    "t'{1:d\n}'",
    "t'{:x}'",
    "t'{=x}'",
    "t'{lambda:1}'",
    "t'{x!s!}'",
    "t'{x!s:'",
    "t'{x!z}'",
    "t'{x!}'",
    "t'{x:{;}}'",
    "t'{x;y}'",
    "t'{x=y}'",
    "t'{x}' = 42\n",
    "t'{}'",
    "t'}'",
    "tb''\n",
    'try',
    'try:',
    'try:\n\t1/0\n    \t1/0\nfinally:\n pass\n',
    'try:\n    if saved is None:\n        boom()\n    raise saved\nexcept KeyError as None:\n    saved = e\n',
    'try:\n    pass\nexcept Exception as a.b:\n    pass',
    'try:\n    pass\nexcept Exception as a[b]:\n    pass',
    'try:\n    pass\nexcept* Exception as a.b:\n    pass',
    'try:\n    pass\nexcept* Exception as a[b]:\n    pass',
    'try:\n   pass\nexcept* TypeError as (obj, name):\n   pass\n',
    'try:\n   pass\nexcept* TypeError as 1:\n   pass\n',
    'try:\n   x = 34\n',
    'try:\n  pass\nexcept A, B, C as blech:\n  pass\n',
    'try:\n  pass\nexcept*:\n  pass',
    'try:\n  pass\nexcept:\n  pass\nexcept ValueError:\n  pass',
    'try:\n pass\nexcept:',
    'try: pass\nexcept* ValueError: pass\nexcept: pass\n',
    'tu"234"\n',
    'type A = (await 3)\n',
    'type A[T = ((x:=3))] = int\n',
    'type A[T: ((x:= 3), int)] = int\n',
    'type A[T: (await 3)] = int\n',
    'type A[T: (x:=3)] = int\n',
    'type A[T=int, U] = int',
    'type T = [(x := 3) for _ in range(2)]',
    'type T[A, *A] = None',
    'type X = (y := 3)',
    'type X = (yield)',
    'type X[**A: (int, str)] = int',
    'type X[**A: str] = int',
    'type X[*A: (int, str)] = int',
    'type X[*A: str] = int',
    'while a:',
    'while a:\n pass\nelse:',
    'with a:',
    'x = 0o9',
    'x = pass if 1 else 1\n',
    'x if x else ',
    'x, b += 3',
    'x=1\nfrom __future__ import division',
    'yield',
    'yield = 1\n',
    'yield from [1,2]\n',
    '{',
    '{**{} for a in [1]}\n',
    '{1, 2, 3} = 42\n',
    '{1: *12+1}\n',
    '{1: 2, 3: 4} = 42\n',
    '{1:2, 3:4, 5}\n',
    '{1:}\n',
    '{x: y for y, x in ((1, 2), (3, 4))} = 5',
    '{y for y in (1,2)} = 10          # doctest: +IGNORE_EXCEPTION_DETAIL\n',
    '}',
]
for source in SOURCES:
    try:
        compile(source, "<test>", "exec")
        result = "compiles"
    except SyntaxError as e:
        result = (type(e).__name__, e.msg, e.lineno, e.offset, e.end_lineno, e.end_offset, e.text)
    print(ascii(source), "=>", result)
