/*
 * Copyright (C) 2026 Oven-sh Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#pragma once

#if USE(BUN_JSC_ADDITIONS)

#include "FFISignature.h"
#include "JSObject.h"
#include "MacroAssemblerCodeRef.h"

namespace JSC {

// A JSFFICallback wraps a JS callable object in a native-ABI entry point
// (SPEC section 9). Native code calls `nativeEntrypoint()` like any C function
// pointer of the callback's signature; the entry thunk marshals the native
// arguments into the canonical slot buffer and re-enters JS through
// ffiCallbackDispatch. Invoking the entry point after the object has been
// collected is undefined behaviour, exactly like Bun's non-threadsafe
// callbacks today: the user must keep the object alive while native code may
// call it.
class JSFFICallback final : public JSNonFinalObject {
public:
    using Base = JSNonFinalObject;

    static constexpr unsigned StructureFlags = Base::StructureFlags;

    // Holds a Ref<FFI::Signature> and the MacroAssemblerCodeRef of the entry
    // thunk, so the cell must run its destructor.
    static constexpr DestructionMode needsDestruction = NeedsDestruction;
    static void destroy(JSCell*);

    template<typename CellType, SubspaceAccess mode>
    static GCClient::IsoSubspace* subspaceFor(VM& vm)
    {
        return vm.ffiCallbackSpace<mode>();
    }

    DECLARE_EXPORT_INFO;

    DECLARE_VISIT_CHILDREN;

    // Creates the cell and generates its native-ABI entry thunk. On failure
    // (`--useJIT=false` / executable allocation disabled, an unsupported
    // architecture, or executable memory exhaustion) an exception is thrown on
    // the global object's throw scope and nullptr is returned, so every
    // creator (BunFFI.cpp, $vm.ffiCallback, testFFI) gets identical error
    // behavior. `callable` must be callable; the JS surface (SPEC section
    // 9.1) is installed by finishCreation.
    JS_EXPORT_PRIVATE static JSFFICallback* create(VM&, JSGlobalObject*, Structure*, JSObject* callable, Ref<FFI::Signature>&&);
    static Structure* createStructure(VM&, JSGlobalObject*, JSValue prototype);

    // The code pointer handed to C. It stays valid for the cell's lifetime;
    // close() does NOT clear it.
    JS_EXPORT_PRIVATE void* nativeEntrypoint() const;

    // The single close() rule (SPEC section 9.1): idempotent, drops nothing
    // native-side (the entry code lives as long as the cell), the JS-visible
    // "ptr" own property is set to null, and m_closed makes $vm / Bun glue
    // reject the object as an FFI argument.
    JS_EXPORT_PRIVATE void close();
    bool isClosed() const { return m_closed; }

    JSObject* callable() const { return m_callable.get(); }
    FFI::Signature& signature() const { return m_signature.get(); }

private:
    JSFFICallback(VM&, Structure*, Ref<FFI::Signature>&&);
    ~JSFFICallback();

    void finishCreation(VM&, JSObject* callable);

    WriteBarrier<JSObject> m_callable;
    Ref<FFI::Signature> m_signature;
    // Native-ABI entry thunk with this cell baked as an immediate; generated by
    // FFI::generateCallbackThunk() in finishCreation. Owned by the cell.
    MacroAssemblerCodeRef<JITThunkPtrTag> m_entryCode;
    bool m_closed { false };
};

} // namespace JSC

#endif // USE(BUN_JSC_ADDITIONS)
