import js

def show(label, f):
    try:
        print(label, "=>", f())
    except BaseException as e:
        print(label, "!!", type(e).__name__, e)

show("Math.max", lambda: js.Math.max(1, 5, 3))
show("Math.PI type", lambda: (type(js.Math.PI).__name__, js.Math.PI))
show("JSON.parse", lambda: js.JSON.parse('{"a": [1, 2.5, "x", null, true]}').a)
show("attr of object", lambda: js.JSON.parse('{"a": {"b": 7}}').a.b)
show("item of object", lambda: js.JSON.parse('{"a": 1}')["a"])
show("missing attr", lambda: js.JSON.parse('{}').nope)
show("set attr", lambda: (o := js.Object(), setattr(o, "k", 5), js.JSON.stringify(o))[-1])
show("set item", lambda: (o := js.Object(), o.__setitem__("k", [1, 2]), js.JSON.stringify(o))[-1])
show("stringify python list", lambda: js.JSON.stringify([1, "a", None, True, 2.0]))
show("stringify python dict", lambda: js.JSON.stringify({"a": 1}))
show("stringify tuple", lambda: js.JSON.stringify((1, 2)))
show("new Map", lambda: (m := js.Map.new(), m.set("k", 1), m.get("k"), m.size)[2:])
show("call constructor", lambda: type(js.Date(0)).__name__)
show("iterate Map", lambda: [list(pair) for pair in js.Map.new([[1, 2], [3, 4]])])
show("iterate Set", lambda: sorted(js.Set.new([3, 1, 2])))
show("len(array)", lambda: len(js.Array.of(1, 2, 3)))
show("array is list", lambda: (type(js.Array.of(1)).__name__, js.Array.of(3, 1, 2) + [9], sorted(js.Array.of(3, 1, 2))))
show("list method on array", lambda: (a := js.Array.of(1), a.append(2), a)[-1])
show("js method on list", lambda: [1, 2, 3].map(lambda x, *rest: x * 2))
show("callback with lambda", lambda: js.Array.of(1, 2, 3).filter(lambda x, *rest: x > 1))
show("string method", lambda: js.String("abc").toUpperCase())
show("py str has js method?", lambda: "abc".toUpperCase())
show("throwing js", lambda: js.JSON.parse("{"))
show("catch by type", lambda: js.decodeURIComponent("%"))
show("isinstance error", lambda: isinstance(js.Error.new("x"), Exception))
show("repr of object", lambda: repr(js.JSON.parse('{"a": 1}')))
show("repr of function", lambda: repr(js.Math.max))
show("str of Date", lambda: str(js.Date.new(0).toISOString()))
show("bool of empty object", lambda: bool(js.Object()))
show("eq identity", lambda: (o := js.Object(), o == o, o == js.Object())[1:])
show("in operator", lambda: "a" in js.JSON.parse('{"a": 1}'))
show("dir", lambda: sorted(dir(js.JSON.parse('{"a": 1, "b": 2}')))[:4])
show("keywords to js", lambda: js.Object.assign(js.Object(), a=1).a)
show("typed array", lambda: bytes(js.Uint8Array.of(104, 105)))
show("promise type", lambda: type(js.Promise.resolve(1)).__name__)
show("symbol", lambda: type(js.Symbol.iterator).__name__)
show("bigint", lambda: js.BigInt(2) ** 70)
show("undefined vs null", lambda: (js.undefined is None, js.JSON.parse("null") is None))
show("int stays int", lambda: (type(js.JSON.parse("3")).__name__, type(js.JSON.parse("3.0")).__name__, type(js.JSON.parse("3.5")).__name__))
show("float to js and back", lambda: type(js.Array.of(2.0)[0]).__name__)
