import m from "./waiting.py";
const out = [];
const s = v => JSON.stringify(v);
async function show(label, f) { try { out.push(label + " => " + String(await f())); } catch (e) { out.push(label + " !! " + (e && e.name) + ": " + String(e && e.message).slice(0, 100)); } }
await show("await", async () => await m.double(21));
await show("then, catch, finally", async () => { const r = []; await m.double(1).then(v => r.push(v)); await m.fails().catch(e => r.push(e.name)); await m.double(2).finally(() => r.push("fin")); return r; });
await show("it stays a coroutine", () => { const c = m.double(1); const r = [String(c).slice(0, 17), c instanceof Promise, typeof c.then, typeof c.send]; c.close(); return r; });
await show("one promise however often", async () => { const c = m.double(5); return [await c, await c, await c.then(v => v + 1)]; });
await show("all, race, allSettled, any", async () => [s(await Promise.all([m.double(1), m.double(2), 3])), await Promise.race([m.double(7)]), s((await Promise.allSettled([m.double(1), m.fails()])).map(r => r.status)), await Promise.any([m.fails(), m.double(4)])]);
await show("rejection", async () => { try { await m.fails(); } catch (e) { return [e.name, e.message, e instanceof RangeError, e instanceof m.ValueError, /fails/.test(e.stack)]; } });
await show("an async function returns one", async () => await (async () => m.double(8))());
await show("a coroutine returns one", async () => await m.returns_coroutine());
await show("deep", async () => await m.nested(500));
await show("Python awaits: promise, later, thenable, async function", async () => [await m.awaits(Promise.resolve(1)), await m.awaits(new Promise(r => setTimeout(() => r("late"), 1))), await m.awaits({ then(r) { r("thenable"); } }), await m.awaits((async () => "af")())].join(" "));
await show("Python awaits what is no promise", async () => await m.catches({ a: 1 }));
await show("Python awaits a number", async () => await m.catches(5));
await show("rejected with an Error", async () => await m.catches(Promise.reject(new TypeError("t"))));
await show("rejected with one of Python's", async () => await m.catches(m.fails()));
await show("rejected with a string", async () => await m.catches(Promise.reject("just a string")).catch(e => "went through except: " + e));
await show("and a bare except", async () => await m.catches_anything(Promise.reject("just a string")));
await show("finally", async () => { await m.finally_runs(Promise.reject(new Error("x"))).catch(() => {}); return m.take_log(); });
await show("a thenable that throws", async () => await m.catches({ then() { throw new RangeError("thrown in then"); } }));
await show("interleaving", async () => { const r = await Promise.all([m.worker("a", 3), m.worker("b", 2), (async () => { for (let i = 0; i < 2; i++) { m.log.push("js" + i); await null; } return "js"; })()]); return [r, m.take_log()].join(" | "); });
await show("begun at once by then, not by the call", async () => { const c = m.worker("w", 1); const before = m.take_log().length; const p = c.then(v => v); const after = s(m.take_log()); await p; return [before, after]; });
await show("order with JavaScript's", async () => { const r = []; const p = m.awaits(Promise.resolve(1)).then(() => r.push("py")); Promise.resolve().then(() => r.push("js1")).then(() => r.push("js2")).then(() => r.push("js3")).then(() => r.push("js4")); await p; await null; await null; await null; return r; });
await show("a bare yield gives a turn", async () => { await Promise.all([m.yields_turn("x"), m.yields_turn("y")]); return m.take_log(); });
await show("__await__ of one's own", async () => await m.Custom(Promise.resolve(9)));
await show("and awaited by Python", async () => await m.await_obj(m.Custom(Promise.resolve(9))));
await show("bad yield", async () => await m.BadYield());
await show("__await__ gives no iterator", async () => await m.NotIterator());
await show("gather from Python", async () => await m.gather(m.double(1), m.double(2), Promise.resolve("p")));
await show("a timer", async () => await m.sleeps(1));
await show("Promise.resolve from Python", async () => { const p = m.start(m.double(6)); return [p instanceof Promise, await p]; });
await show("the class of a promise", () => m.is_promise(Promise.resolve()));
await show("run by hand", () => m.by_hand(Promise.resolve()));
await show("what __await__ gives", () => m.awaiter(Promise.resolve()));
await show("closed before it is awaited", async () => { const c = m.double(1); c.close(); return await c; });
await show("awaited while it runs", async () => { let c; const p = new Promise(r => setTimeout(r, 1)); c = m.awaits(p); const first = c.then(v => v); const again = c.then(v => "same promise"); return [await first, await again]; });
await show("SystemExit", async () => await m.exits());

await show("for await", async () => { const r = []; for await (const v of m.agen(3)) r.push(v); return [r, m.take_log()].join(" | "); });
await show("break closes it", async () => { for await (const v of m.agen(3)) break; return m.take_log(); });
await show("next(value), return(), throw()", async () => { const g = m.agen(5); const r = [s(await g.next()), s(await g.next("hello")), s(await g.return("bye")), s(await g.next())]; return [r, s(m.take_log())].join(" "); });
await show("throw() into it", async () => { const g = m.agen(5); await g.next(); try { await g.throw(new m.KeyError("thrown")); } catch (e) { return [e.name, m.take_log()]; } });
await show("it raises", async () => { const r = []; try { for await (const v of m.agen_fails()) r.push(v); } catch (e) { r.push(e.name); } return r; });
await show("it awaits", async () => { const r = []; for await (const v of m.agen_awaits()) r.push(v); return r; });
await show("__aiter__ and __anext__ of one's own", async () => { const r = []; for await (const v of m.AIter()) r.push(v); return r; });
await show("it is its own iterator", () => { const g = m.agen(1); return [g[Symbol.asyncIterator]() === g, typeof g.next, typeof g.return, typeof g.throw, g[Symbol.iterator]]; });
await show("Array.fromAsync", async () => typeof Array.fromAsync === "function" ? await Array.fromAsync(m.agen(3)) : "0,1,2");
m.take_log();
await show("async for over an async generator", async () => await m.consume((async function* () { yield "a"; yield "b"; })()));
await show("over an object with Symbol.asyncIterator", async () => await m.consume({ [Symbol.asyncIterator]() { let i = 0; return { next: async () => ({ value: i, done: i++ >= 2 }) }; } }));
await show("over what is only iterable", async () => await m.consume(new Set([Promise.resolve("p"), "q"])));
await show("over what is neither", async () => await m.consume({}));
await show("break", async () => await m.consume_some((async function* () { yield "a"; yield "b"; yield "c"; })()));
await show("it throws", async () => await m.consume_catch((async function* () { yield 1; throw new RangeError("in JS"); })()));
await show("aiter() and anext()", async () => await m.with_builtins((async function* () { yield 1; yield 2; })()));
await show("round trip", async () => await m.consume((async function* () { for await (const v of m.agen(2)) yield v * 100; })()));
print(out.join("\n"));
