name: CI

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    uses: ./.github/workflows/build-reusable.yml
    with:
      build_ref: ${{ github.sha }}
      release_tag: autobuild-${{ github.sha }}
      is_prerelease: false
