name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linux_amd64:
    name: Linux AMD64
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Run
        run: |
          rm -rf /tmp/bun-webkit
          temp=/tmp bash release.sh
      - uses: actions/upload-artifact@v3
        with:
          name: bun-webkit-linux-amd64
          path: /tmp/bun-webkit/bun-webkit-linux-amd64.tar.gz
