name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["icu-build-test"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    strategy:
      matrix:
        include:
          - runner: windows-latest
            build-type: Release
            arch: amd64
    runs-on: windows-latest
    timeout-minutes: 90
    steps:
      - uses: KyleMayes/install-llvm-action@1a3da29f56261a1e1f937ec88f0856a9b8321d7e
        with:
          version: 16.0.6
      - run: choco install -y ninja
      - uses: actions/checkout@v4
      - name: Build WebKit
        run: |
          $env:Path = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\;" + $env:Path
          $env:WEBKIT_OUTPUT_DIR = "bun-webkit"
          $env:BUN_WEBKIT_VERSION = "${{ github.sha }}"
          $env:CMAKE_BUILD_TYPE = "${{matrix.build-type}}"
          ./windows-release.ps1
      - uses: actions/upload-artifact@v3
        with:
          name: bun-webkit-windows-${{ matrix.arch }}
          path: bun-webkit.tar.gz
