name: Windows

on:
  push:
    branches: [windows-ci]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - run: ./windows-release.ps1
      - uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: bun-webkit-x64
